#!/usr/bin/env python3
"""Generate query files that measure a shipped SwiftQL build (issue #789).

`generate.py` measures stand-in surfaces built from the shipped declarations.
This generator writes queries against a real SwiftQL build instead, so the
same body can be type-checked against two builds of the package, such as the
base branch and a branch that changes the query surface.

Every file declares the same `@SQLTable` model, whose columns are the ones
`generate.py` gives its scope, and one query body. The body is a result
builder of N clauses, each one of `generate.CLAUSE_SHAPES`, as in the stand-in
harness. The chain bodies hold a single `Where` whose predicate joins N
comparisons with `&&`: one expression, which the type checker solves as a
whole, unlike the separate clauses of the other bodies. The `setting` bodies
hold one `Setting` closure of N assignments, and `columns-10` and `row-6` one
call of `columns(...)` and of `#row(...)`: the macros' value slots (issue
#825).

Usage: generate_shipped.py <output-directory>
"""

import os
import sys

COLUMNS = [
    ("text0", "String"),
    ("text1", "String"),
    ("text2", "String?"),
    ("count0", "Int"),
    ("count1", "Int"),
    ("count2", "Int?"),
    ("amount0", "Double"),
    ("amount1", "Double?"),
    ("flag0", "Bool"),
    ("flag1", "Bool?"),
]

# The shapes `generate.py` measures, written against the real API. The real
# surface has no `year()` on a text column, so that shape reads the year
# through `strftime`, which SQLite does have.
CLAUSE_SHAPES = [
    "scope.text0 == text",
    "scope.count0 > count",
    "scope.amount0 <= amount",
    "scope.text1 != text",
    "scope.count1 >= count",
    "(scope.text0 + scope.text1) == text",
    "(scope.count0 + scope.count1) > count",
    "(scope.count0 * scope.count1) < count",
    "scope.text2 == text",
    "scope.count2 >= count",
    "!(scope.flag0)",
    "scope.flag0 && (scope.count0 == count)",
    "(scope.text0 == text) || (scope.count1 != count)",
    "(scope.amount0 * scope.amount0) >= amount",
    "(scope.count0 - scope.count1) == count",
    "scope.flag1 && (scope.text1 == text)",
    "scope.text2.isNull()",
    "scope.text0.strftime(\"%Y\") == text",
    "scope.count0.toString() == text",
    "scope.text1.toDouble() <= amount",
]

CHAIN_TERMS = [
    "scope.text0 == text",
    "scope.count0 > count",
    "scope.amount0 <= amount",
    "scope.text2 == text",
    "scope.count1 != count",
    "scope.flag0 == true",
    "scope.count2 >= count",
    "scope.text1 != text",
]

# The lengths of the && chains, with and without a mistake in the last term.
CHAIN_LENGTHS = (2, 4, 6, 8, 12, 16)

# The assignments of a `Setting` body (issue #825), one statement each. A
# value slot takes a Swift value, `nil`, a column, or a composed expression.
SETTING_ASSIGNMENTS = [
    "row.text0 = text",
    "row.count0 = scope.count0 + count",
    "row.amount0 = scope.amount0 * amount",
    "row.text2 = nil",
    "row.count2 = count",
    "row.text1 = scope.text0 + text",
    "row.flag0 = scope.count1 > count",
    "row.amount1 = amount",
    "row.count1 = scope.count1 - count",
    "row.flag1 = scope.flag0",
]

# The number of assignments in the `Setting` bodies.
SETTING_LENGTHS = (10, 40, 120)

# One argument for each column of `GateRow.columns(...)`, in declaration
# order (issue #825).
COLUMNS_ARGUMENTS = [
    "text0: scope.text0 + text",
    "text1: scope.text1",
    "text2: scope.text2",
    "count0: scope.count0 + count",
    "count1: scope.count1 * count",
    "count2: scope.count2",
    "amount0: scope.amount0 * amount",
    "amount1: scope.amount1",
    "flag0: scope.count0 > count",
    "flag1: scope.flag1",
]

# The arguments of one `#row(...)`, which takes at most six (issue #825).
ROW_ARGUMENTS = [
    "scope.text0 + text",
    "scope.count0 + count",
    "scope.amount0 * amount",
    "scope.text2",
    "scope.count0 > count",
    "scope.flag1",
]

PRELUDE = """// Generated by Research/DialectParameterTypeCheck/generate_shipped.py. Do not edit.
import SwiftQL

@SQLTable struct GateRow {
""" + "".join(f"    let {name}: {kind}\n" for name, kind in COLUMNS) + """}

@resultBuilder
enum GateQueryBuilder {
    static func buildBlock(_ clauses: any XLEncodable...) -> [any XLEncodable] {
        clauses
    }
}
"""


def write_clauses(path, count):
    lines = [
        PRELUDE,
        "@GateQueryBuilder",
        "func gateQuery(text: String, count: Int, amount: Double) -> [any XLEncodable] {",
        "    let scope = XLSchema().table(GateRow.self)",
    ]
    for index in range(count):
        lines.append(f"    {CLAUSE_SHAPES[index % len(CLAUSE_SHAPES)]}")
    lines.append("}")
    with open(path, "w") as handle:
        handle.write("\n".join(lines) + "\n")


def write_chain(path, count, mistake=None):
    terms = [CHAIN_TERMS[index % len(CHAIN_TERMS)] for index in range(count)]
    if mistake is not None:
        terms[-1] = mistake
    lines = [
        PRELUDE,
        "func gateQuery(text: String, count: Int, amount: Double) -> any XLQueryStatement<GateRow> {",
        "    sql { schema in",
        "        let scope = schema.table(GateRow.self)",
        "        Select(scope)",
        "        From(scope)",
        "        Where(" + " && ".join(terms) + ")",
        "    }",
        "}",
    ]
    with open(path, "w") as handle:
        handle.write("\n".join(lines) + "\n")


def write_setting(path, count):
    lines = [
        PRELUDE,
        "func gateQuery(text: String, count: Int, amount: Double) -> any XLUpdateStatement {",
        "    sql { schema in",
        "        let scope = schema.into(GateRow.self)",
        "        Update(scope)",
        "        Setting<GateRow> { row in",
    ]
    for index in range(count):
        lines.append(f"            {SETTING_ASSIGNMENTS[index % len(SETTING_ASSIGNMENTS)]}")
    lines += [
        "        }",
        "    }",
        "}",
    ]
    with open(path, "w") as handle:
        handle.write("\n".join(lines) + "\n")


def write_projection(path, projection):
    lines = [
        PRELUDE,
        "func gateQuery(text: String, count: Int, amount: Double) -> any XLQueryStatement<GateRow> {",
        "    sql { schema in",
        "        let scope = schema.table(GateRow.self)",
        f"        Select({projection})",
        "        From(scope)",
        "    }",
        "}",
    ]
    with open(path, "w") as handle:
        handle.write("\n".join(lines) + "\n")


def write_row(path):
    # `#row` of six columns needs Swift 6.1, as the macro does (issue #408).
    lines = [
        PRELUDE,
        "func gateQuery(text: String, count: Int, amount: Double) -> any XLEncodable {",
        "    let scope = XLSchema().table(GateRow.self)",
        "    return #row(" + ", ".join(ROW_ARGUMENTS) + ")",
        "}",
    ]
    with open(path, "w") as handle:
        handle.write("\n".join(lines) + "\n")


def main():
    output = sys.argv[1]
    os.makedirs(output, exist_ok=True)
    for count in (30, 120, 450):
        write_clauses(os.path.join(output, f"clauses-{count}.swift"), count)
    for count in SETTING_LENGTHS:
        write_setting(os.path.join(output, f"setting-{count}.swift"), count)
    write_projection(
        os.path.join(output, "columns-10.swift"),
        "GateRow.columns(" + ", ".join(COLUMNS_ARGUMENTS) + ")",
    )
    write_row(os.path.join(output, "row-6.swift"))
    for count in CHAIN_LENGTHS:
        write_chain(os.path.join(output, f"chain-{count}.swift"), count)
    for count in CHAIN_LENGTHS:
        write_chain(
            os.path.join(output, f"chain-misspelled-{count}.swift"),
            count,
            mistake="scope.txet0 == text",
        )
        write_chain(
            os.path.join(output, f"chain-wrong-type-{count}.swift"),
            count,
            mistake="scope.count0 == text",
        )


if __name__ == "__main__":
    main()
