//
//  SQLFunctionMacroExecutionTests.swift
//  SwiftQL
//
//  Downstream execution coverage for the `@SQLFunction` macro: functions whose `definition` and
//  `makeSQL(context:)` are generated by the macro (rather than hand-written, as in
//  `HaversineDistance` and `ColumnReadIntegerFunction`) are registered on a real database and
//  executed through real SQLite, across zero, one, and many argument shapes.
//

import Foundation
import GRDB
import XCTest
@testable import SwiftQL


/// Mirrors `HaversineDistance` (see `SQLExampleTests.swift` and the `CustomFunctions.md` guide),
/// but the `definition` and `makeSQL(context:)` members below are generated by `@SQLFunction`
/// instead of hand-written.
@SQLFunction(name: "macroHaversineDistance")
struct MacroHaversineDistance: XLCustomFunction {

    typealias T = Double

    private let fromLatitude: any XLExpression<Double>
    private let fromLongitude: any XLExpression<Double>
    private let toLatitude: any XLExpression<Double>
    private let toLongitude: any XLExpression<Double>

    init(
        fromLatitude: any XLExpression<Double>,
        fromLongitude: any XLExpression<Double>,
        toLatitude: any XLExpression<Double>,
        toLongitude: any XLExpression<Double>
    ) {
        self.fromLatitude = fromLatitude
        self.fromLongitude = fromLongitude
        self.toLatitude = toLatitude
        self.toLongitude = toLongitude
    }

    static func execute(reader: XLColumnReader) throws -> Double {
        let latA = try radians(degrees: reader.readReal(at: 0))
        let lonA = try radians(degrees: reader.readReal(at: 1))
        let latB = try radians(degrees: reader.readReal(at: 2))
        let lonB = try radians(degrees: reader.readReal(at: 3))
        let deltaLat = latB - latA
        let deltaLon = lonB - lonA
        let a = pow(sin(deltaLat / 2), 2)
            + cos(latA) * cos(latB) * pow(sin(deltaLon / 2), 2)
        return 2 * 6371 * asin(Swift.min(1, sqrt(a)))
    }

    private static func radians(degrees: Double) -> Double {
        (degrees / 180) * .pi
    }
}


/// Mirrors `ColumnReadIntegerFunction` (see `SQLColumnReadErrorTests.swift`), with a single
/// macro-generated argument.
@SQLFunction(name: "macroDoubleValue")
struct MacroDoubleValueFunction: XLCustomFunction {

    typealias T = Int

    private let value: any XLExpression<Int>

    init(_ value: any XLExpression<Int>) {
        self.value = value
    }

    static func execute(reader: XLColumnReader) throws -> Int {
        try reader.readInteger(at: 0) * 2
    }
}


/// A zero-argument function, exercising the macro's empty-parameter-list shape.
@SQLFunction(name: "macroAnswerToEverything")
struct MacroAnswerFunction: XLCustomFunction {

    typealias T = Int

    static func execute(reader: XLColumnReader) throws -> Int {
        42
    }
}


final class SQLFunctionMacroExecutionTests: XCTestCase {

    private var database: GRDBDatabase!
    private var databasePool: DatabasePool!
    private var databaseDirectoryURL: URL!

    override func setUpWithError() throws {
        databaseDirectoryURL = FileManager.default.temporaryDirectory
            .appendingPathComponent(UUID().uuidString, isDirectory: true)
        try FileManager.default.createDirectory(
            at: databaseDirectoryURL,
            withIntermediateDirectories: true
        )
        let fileURL = databaseDirectoryURL.appendingPathComponent(
            "database.sqlite",
            isDirectory: false
        )
        var builder = try GRDBDatabaseBuilder(
            url: fileURL,
            configuration: Configuration(),
            logger: nil
        )
        builder.addFunction(MacroHaversineDistance.self)
        builder.addFunction(MacroDoubleValueFunction.self)
        builder.addFunction(MacroAnswerFunction.self)
        database = try builder.build()
        databasePool = database.databasePool
    }

    override func tearDown() {
        databasePool = nil
        database = nil
        try? FileManager.default.removeItem(at: databaseDirectoryURL)
        databaseDirectoryURL = nil
    }

    /// Registers a macro-generated four-argument function and confirms real SQLite renders and
    /// executes the generated `makeSQL(context:)` call correctly, using the same coordinates and
    /// expected distance as the hand-written `HaversineDistance` example.
    func testMacroGeneratedFunctionWithManyArgumentsComputesHaversineDistance() throws {
        let myLatitude = XLNamedBindingReference<Double>(name: "myLatitude")
        let myLongitude = XLNamedBindingReference<Double>(name: "myLongitude")
        let statement = sqlQuery { schema in
            let restaurant = schema.table(Restaurant.self)
            let result = NearbyRestaurant.columns(
                name: restaurant.name,
                distance: MacroHaversineDistance(
                    fromLatitude: myLatitude,
                    fromLongitude: myLongitude,
                    toLatitude: restaurant.latitude,
                    toLongitude: restaurant.longitude
                ).rounded(to: 2)
            )
            return select(result).from(restaurant).orderBy(result.distance.ascending())
        }

        try databasePool.write { database in
            try database.execute(
                sql: "CREATE TABLE Restaurant (name TEXT NOT NULL, latitude DOUBLE NOT NULL, longitude DOUBLE NOT NULL)"
            )
            try database.execute(
                sql: "INSERT INTO Restaurant (name, latitude, longitude) VALUES (?, ?, ?)",
                arguments: ["Magica Roma", -33.891851, 18.561470]
            )
        }

        let request = database.makeRequest(with: statement)
        let layout = request.parameterLayout
        let coordinates = try XLInvocationBindings<XLSQLiteValue>(
            layout: layout,
            bindings: [
                try XLInvocationBinding(
                    slot: try XCTUnwrap(layout.slot(for: .named("myLatitude"))),
                    value: .real(-33.877873677687894)
                ),
                try XLInvocationBinding(
                    slot: try XCTUnwrap(layout.slot(for: .named("myLongitude"))),
                    value: .real(18.488075015723)
                ),
            ]
        ).validatingComplete()

        let rows = try request.fetchAll(bindings: coordinates)
        XCTAssertEqual(rows, [NearbyRestaurant(name: "Magica Roma", distance: 6.95)])
    }

    /// Registers a macro-generated one-argument function and executes it as a real SQLite scalar
    /// expression.
    func testMacroGeneratedFunctionWithOneArgumentDoublesValue() throws {
        let result = try databasePool.read { database in
            try Int.fetchOne(database, sql: "SELECT macroDoubleValue(21)")
        }
        XCTAssertEqual(result, 42)
    }

    /// Registers a macro-generated zero-argument function and executes it as a real SQLite scalar
    /// expression.
    func testMacroGeneratedFunctionWithZeroArgumentsReturnsConstant() throws {
        let result = try databasePool.read { database in
            try Int.fetchOne(database, sql: "SELECT macroAnswerToEverything()")
        }
        XCTAssertEqual(result, 42)
    }
}
