//
//  MetaModel.swift
//  SwiftQL
//
//  The syntax-free description of an `@SQLTable`/`@SQLResult` declaration, and
//  the property value it is made of.
//
//  Split out of MetaBuilder.swift (issue #564). The file had a clean fault
//  line: one half consumed SwiftSyntax and produced properties, the other
//  consumed only properties and names and produced strings. Everything below
//  belongs to neither half -- it is what they pass between them.
//

import Foundation


internal struct MetaProperty {
    
    enum ColumnKind {
        
        case reference
        
        case result
    }
    
    enum Mutability {
        
        case mutable
        
        case immutable
    }
    
    var mutability: Mutability
    var name: String
    var alias: String
    var optional: Bool
    var type: String

    /// The trimmed source text of the single argument passed to this property's `@SQLCodec(_:)`
    /// attribute (issue #66), or `nil` if the property declares no explicit codec selection. The
    /// macro never evaluates this expression -- it is spliced verbatim into generated code as a
    /// `.explicit(...)` codec-key reference, so it is resolved with the same visibility as the
    /// property's own declaration.
    var codecKeyExpression: String? = nil

    var qualifiedType: String {
        if optional {
            type + "?"
        }
        else {
            type
        }
    }
    
    func columnType(kind: ColumnKind) -> String {
        switch kind {
        case .reference:
            "XLColumnReference<\(qualifiedType)>"
        case .result:
            "XLColumnResult<\(qualifiedType)>"
        }
    }

    func makePropertyDecl() -> String {
        "public let \(name): \(qualifiedType)"
    }

    func makeColumnPropertyDecl(kind: ColumnKind) -> String {
        "public let \(name): \(columnType(kind: kind))"
    }
    
    func makeInstance(kind: ColumnKind, dependency: String) -> String {
        "\(columnType(kind: kind))(dependency: \(dependency), as: \"\(alias)\")"
    }
}


///
/// Hands out generated identifiers that cannot collide with names already in
/// scope.
///
/// A generated member sits alongside the author's own declarations, so a name
/// the macro picks freely -- a loop variable, a temporary -- can shadow or
/// redeclare one of theirs. Each allocation takes `base` when it is free and
/// otherwise appends the lowest `_N` that is not, and every name handed out is
/// remembered, so two allocations of the same base never agree.
///
/// Internal rather than private so its algorithm can be tested directly; it is
/// otherwise only used from `MetaBuilder`.
internal struct GeneratedIdentifierAllocator {
    private var used: Set<String>

    init(used: Set<String>) {
        self.used = used
    }

    mutating func allocate(_ base: String) -> String {
        var candidate = base
        var suffix = 0
        while used.contains(candidate) {
            suffix += 1
            candidate = "\(base)_\(suffix)"
        }
        used.insert(candidate)
        return candidate
    }
}


///
/// Everything the emitters need about one annotated declaration, and nothing
/// about the syntax it was parsed from.
///
/// The emitters take this rather than a `StructDeclSyntax` so their output is a
/// function of names and properties alone: a fixture can be built by hand, and
/// an emitter test does not have to parse source to say what it means.
///
internal struct MetaModel {

    /// Property names which collide with members generated by the macro (e.g. on `MetaResult` or
    /// `MetaWritableTable`), and would produce duplicate declarations in the expanded code.
    ///
    /// `staticResultField` is reserved unconditionally (issue #66 review feedback), even though
    /// the macro only emits a `staticResultField(_:...)` overload when some property on the type
    /// carries `@SQLCodec`. A property literally named `staticResultField` on a type that does
    /// use `@SQLCodec` would otherwise compile -- an instance stored property and a static
    /// function sharing one base name do not collide in Swift -- but the resulting
    /// `Type.staticResultField(...)` call site becomes genuinely confusing to read, and whether
    /// the macro emits the static overload at all depends on unrelated properties elsewhere in
    /// the same declaration. Reserving the name always gives one focused diagnostic instead of a
    /// conditional trap.
    static let reservedPropertyNames: Set<String> = [
        "_table",
        "_namespace",
        "_dependency",
        "_iterator",
        "Row",
        "RowIterator",
        "Dependency",
        "Basis",
        "Nullable",
        "_swiftQLPropertyCodecKeys",
        "staticResultField",
    ]

    /// Name of the struct defined in the Swift source file.
    let structName: String

    /// Name of the SQL table which the struct refers to. SwiftQL uses the
    /// struct name for the table name unless the `name:` parameter is specified
    /// in the macro. Only applies to `SQLTable` macros.
    let tableName: String

    /// Generic parameter names declared on the struct, if any. Kept because a
    /// generated generic or local must not shadow one of them.
    let genericParameterNames: [String]

    /// Non-optional properties defined on the struct. These properties
    /// correspond to table columns.
    let properties: [MetaProperty]

    /// Optional properties defined on the struct. These properties correspond
    /// to nullable table columns.
    let optionalProperties: [MetaProperty]

    /// Anonymous (unnamed) properties. Only applies to `SQLResult` macros.
    /// > TODO: Remove anonymous properties.
    let anonymousProperties: [MetaProperty]

    /// Optional anonymous properties. Only applies to `SQLResult` macros.
    /// > TODO: Remove optional anonymous properties.
    let anonymousOptionalProperties: [MetaProperty]

    /// Mutable properties defined on the struct.
    let mutableProperties: [MetaProperty]

    init(
        structName: String,
        tableName: String,
        genericParameterNames: [String] = [],
        properties: [MetaProperty]
    ) {
        self.structName = structName
        self.tableName = tableName
        self.genericParameterNames = genericParameterNames
        self.properties = properties
        self.optionalProperties = properties.map {
            MetaProperty(mutability: $0.mutability, name: $0.name, alias: $0.alias, optional: true, type: $0.type)
        }
        self.anonymousProperties = properties.map {
            MetaProperty(mutability: $0.mutability, name: $0.name, alias: $0.alias, optional: $0.optional, type: $0.type)
        }
        self.anonymousOptionalProperties = properties.map {
            MetaProperty(mutability: $0.mutability, name: $0.name, alias: $0.alias, optional: true, type: $0.type)
        }
        self.mutableProperties = properties.filter {
            $0.mutability == .mutable
        }
    }

    /// Identifiers that generated method generics and locals must not shadow.
    ///
    /// Property types are included because a generated generic named like a
    /// concrete type would silently change the meaning of that type inside the
    /// generated signature. The nominal name is included because a generated
    /// local can otherwise shadow a return type with the same spelling.
    var generatedIdentifierReservations: Set<String> {
        var identifiers: Set<String> = [structName]
        identifiers.formUnion(genericParameterNames)
        for property in properties {
            identifiers.insert(property.alias)
            identifiers.formUnion(Self.identifiers(in: property.type))
            identifiers.formUnion(Self.identifiers(in: property.qualifiedType))
        }
        return identifiers
    }

    private static func identifiers(in source: String) -> Set<String> {
        Set(
            source.split { character in
                character != "_"
                    && !character.isLetter
                    && !character.isNumber
            }.map(String.init)
        )
    }

}
