//
//  MetaBuilder+Result.swift
//  SwiftQL
//
//  Emission of the metadata every annotated model gets, table or not: the
//  nested `Nullable`, the four `Meta*Result` shapes, the common-table and
//  reader types, the anonymous-result factories, and the memberwise
//  initializer.
//
//  Split out of MetaBuilder.swift (issue #564).
//

import Foundation


extension MetaBuilder {

    func makeMetaResultExtension(table: Bool) -> String {
        var context = CodeWriter()
        context.block("extension \(structName): XLResult") { context in
            
            makeCommonMeta(context: &context, table: table)
        }
        return context.build()
    }

    // Swift 5.9 does not reliably expose static members generated by an ExtensionMacro to
    // cross-file lookup (https://github.com/swiftlang/swift/issues/67989). Generate the public
    // projection factory through the MemberMacro role so `.columns(...)` remains available on
    // every supported compiler.

    private func makeCommonMeta(context: inout CodeWriter, table: Bool) {
        
        var properties: [MetaProperty]
        var optionalProperties: [MetaProperty]
        let columnKind: MetaProperty.ColumnKind
        if table {
            // Table
            columnKind = .reference
            properties = self.properties
            optionalProperties = self.optionalProperties
        }
        else {
            // Select result
            columnKind = .result
            properties = self.anonymousProperties
            optionalProperties = self.anonymousOptionalProperties

        }

        // Nullable
        context.block("public struct Nullable: XLMetaNullable") { context in
            
            context.line("public typealias Basis = \(structName)")
            
            for property in optionalProperties {
                context.line(property.makePropertyDecl())
            }
        }

        // The four metadata shapes. Named or not, nullable or not.
        for shape in [
            MetaResultShape(
                typeName: "MetaResult",
                protocolName: "XLMetaResult",
                rowType: structName,
                dependencyType: "XLTableDeclaration",
                properties: properties
            ),
            MetaResultShape(
                typeName: "MetaNamedResult",
                protocolName: "XLMetaNamedResult",
                rowType: structName,
                dependencyType: "XLNamedTableDeclaration",
                properties: properties
            ),
            MetaResultShape(
                typeName: "MetaNullableResult",
                protocolName: "XLMetaNullableResult",
                rowType: "\(structName).Nullable",
                dependencyType: "XLTableDeclaration",
                properties: optionalProperties
            ),
            MetaResultShape(
                typeName: "MetaNullableNamedResult",
                protocolName: "XLMetaNullableNamedResult",
                rowType: "\(structName).Nullable",
                dependencyType: "XLNamedTableDeclaration",
                properties: optionalProperties
            ),
        ] {
            emitMetaResultStruct(shape, columnKind: columnKind, into: &context)
        }

        // MetaCommonTable
        context.block("public struct MetaCommonTable: XLMetaCommonTable") { context in
            
            context.line("public typealias Result = \(structName)")

            context.line("public let definition: XLCommonTableDependency")

            context.block("public init(commonTable: XLCommonTableDependency)") { context in
                context.line("self.definition = commonTable")
            }
        }

        // Reader
        var readerAllocator = GeneratedIdentifierAllocator(
            used: generatedIdentifierReservations
        )
        let rowReader = readerAllocator.allocate("_swiftQLRowReader")
        context.block("public struct SQLReader: XLRowReadable") { context in

            context.line("public typealias Row = \(structName)")

            for property in properties {
                context.line("private let \(property.name): any SwiftQL.XLExpression<\(property.qualifiedType)>")
            }

            var parameters: [String] = []
            for property in properties {
                parameters.append("\(property.name): any SwiftQL.XLExpression<\(property.qualifiedType)>")
            }
            context.block("public init(\(parameters.joined(separator: ", ")))") { context in
                for property in properties {
                    context.line("self.\(property.name) = \(property.name)")
                }
            }

            context.block("public func readRow(reader \(rowReader): XLRowReader) throws -> \(structName)") { context in
                context.declaration("\(structName)") { context in
                    for property in properties {
                        context.item { context in
                            context.line("\(property.name): try \(rowReader).staticColumn(\(property.name), alias: \(quoted(property.alias)))")
                        }
                    }
                }
            }
        }
    
        // Static methods
        
        context.block("public static func makeSQLCommonTable(namespace: XLNamespace, dependency: XLCommonTableDependency) -> MetaCommonTable") { context in
            context.line("MetaCommonTable(commonTable: dependency)")
        }

        // The two shapes whose rows the caller assembles.
        for (functionName, dependencyType, metaType) in [
            ("makeSQLAnonymousResult", "XLTableDeclaration", "MetaResult"),
            ("makeSQLAnonymousNamedResult", "XLNamedTableDeclaration", "MetaNamedResult"),
        ] {
            emitIteratorResultFactory(
                functionName: functionName,
                dependencyType: dependencyType,
                metaType: metaType,
                properties: anonymousProperties,
                columnKind: columnKind,
                into: &context
            )
        }

        // The four that read rows themselves. Their arguments are spelled in
        // the enclosing model's column kind while their rows are always read as
        // results, which is why the two kinds are separate.
        for shape in [
            ResultShape(
                functionName: "makeSQLAnonymousResult",
                dependencyType: "XLTableDeclaration",
                metaType: "MetaResult",
                rowType: structName,
                properties: anonymousProperties,
                parameterColumnKind: columnKind,
                rowColumnKind: .result,
                usesExplicitReturn: true
            ),
            ResultShape(
                functionName: "makeSQLAnonymousNamedResult",
                dependencyType: "XLNamedTableDeclaration",
                metaType: "MetaNamedResult",
                rowType: structName,
                properties: anonymousProperties,
                parameterColumnKind: columnKind,
                rowColumnKind: .result,
                usesExplicitReturn: true
            ),
            ResultShape(
                functionName: "makeSQLAnonymousNullableResult",
                dependencyType: "XLTableDeclaration",
                metaType: "MetaNullableResult",
                rowType: "Nullable",
                properties: anonymousOptionalProperties,
                parameterColumnKind: columnKind,
                rowColumnKind: .result,
                usesExplicitReturn: true
            ),
            ResultShape(
                functionName: "makeSQLAnonymousNullableNamedResult",
                dependencyType: "XLNamedTableDeclaration",
                metaType: "MetaNullableNamedResult",
                rowType: "Nullable",
                properties: anonymousOptionalProperties,
                parameterColumnKind: columnKind,
                rowColumnKind: .result,
                usesExplicitReturn: true
            ),
        ] {
            emitResultFactory(shape, into: &context)
        }
    }

    func makeMemberwizeInitializer() -> String {
        var context = CodeWriter()
        var parameters: [String] = []
        for property in properties {
            parameters.append("\(property.name): \(property.qualifiedType)")
        }
        context.block("public init(\(parameters.joined(separator: ", ")))") { context in
            for property in properties {
                context.line("self.\(property.name) = \(property.name)")
            }
        }
        return context.build()
    }
}
