//
//  MetaBuilder.swift
//  
//
//  Created by Luke Van In on 2024/09/20.
//

import Foundation
import SwiftCompilerPlugin
import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacros


// MARK: - Builder


internal struct MetaProperty {
    
    enum ColumnKind {
        
        case reference
        
        case result
    }
    
    enum Mutability {
        
        case mutable
        
        case immutable
    }
    
    var mutability: Mutability
    var name: String
    var alias: String
    var optional: Bool
    var type: String
    
    var qualifiedType: String {
        if optional {
            type + "?"
        }
        else {
            type
        }
    }
    
    func columnType(kind: ColumnKind) -> String {
        switch kind {
        case .reference:
            "XLColumnReference<\(qualifiedType)>"
        case .result:
            "XLColumnResult<\(qualifiedType)>"
        }
    }

    func makePropertyDecl() -> String {
        "public let \(name): \(qualifiedType)"
    }

    func makeColumnPropertyDecl(kind: ColumnKind) -> String {
        "public let \(name): \(columnType(kind: kind))"
    }
    
    func makeInstance(kind: ColumnKind, dependency: String) -> String {
        "\(columnType(kind: kind))(dependency: \(dependency), as: \"\(alias)\")"
    }
}


#warning("TODO: Remove anonymous properties")

///
/// Generates code for `SQLTable` and `SQLResult` macros.
///
/// Used internally by SwiftQL to generate code for `SQLTable` and `SQLResult` macros.
///
internal struct MetaBuilder {
    
    /// Property names which collide with members generated by the macro (e.g. on `MetaResult` or
    /// `MetaWritableTable`), and would produce duplicate declarations in the expanded code.
    private static let reservedPropertyNames: Set<String> = [
        "_table",
        "_namespace",
        "_dependency",
        "_iterator",
        "Row",
        "RowIterator",
        "Dependency",
        "Basis",
        "Nullable",
    ]

    /// Name of the struct defined in the Swift source file.
    let structName: String
    
    /// Name of the SQL table which the struct refers to. SwiftQL uses the struct name for the table name
    /// unless the `name:` parameter is specified in the macro. Only applies to `SQLTable` macros.
    let tableName: String
    
    /// SwiftSyntax declaration of the struct.
    let declaration: StructDeclSyntax
    
    /// Non-optional properties defined on the struct. These properties correspond to table columns.
    let properties: [MetaProperty]
    
    /// Optional properties defined on the struct. These properties correspond to nullable table columns.
    let optionalProperties: [MetaProperty]
    
    /// Anonymous (unnamed) properties. Only applies to `SQLResult` macros.
    /// > TODO: Remove anonymous properties.
    let anonymousProperties: [MetaProperty]
    
    /// Optional anonymous  properties. Only applies to `SQLResult` macros.
    /// > TODO: Remove optional anonymous properties.
    let anonymousOptionalProperties: [MetaProperty]

    /// Mutable properties defined on the struct.
    let mutableProperties: [MetaProperty]

    ///
    /// Convenience initializer used to initialise the builder with a `DeclGroupSyntax`.
    /// - throws: `SQLMacroError.unsupportedType` if the declaration is not a `StructDeclSyntax`
    ///
    init(node: AttributeSyntax, declaration: DeclGroupSyntax) throws {
        guard let declaration = declaration.as(StructDeclSyntax.self) else {
            throw SQLMacroError.unsupportedType
        }
        try self.init(node: node, declaration: declaration)
    }
    
    ///
    /// Initialises the builder with a node and a declaration.
    ///
    /// - Parameter node: Reference to the macro. E.g. `@SQLTable(name: "foo")`
    /// - Parameter declaration: Reference to the struct which the macro is defined on.
    ///
    /// The initializer collects the properties defined on the struct, to be used in generating the meta data
    /// for the table or result.
    ///
    init(node: AttributeSyntax, declaration: StructDeclSyntax) throws {
        self.structName = declaration.name.text
        self.declaration = declaration

        var diagnostics: [Diagnostic] = []

        // Use the name parameter from the macro if it is defined, otherwise
        // use the name of the struct for the table name.
        if
            case let .argumentList(arguments) = node.arguments,
            let nameArg = arguments.first(where: { $0.label?.text == "name" })
        {
            if
                let nameLiteral = nameArg.expression.as(StringLiteralExprSyntax.self),
                nameLiteral.segments.count == 1,
                case let .stringSegment(nameString)? = nameLiteral.segments.first
            {
                self.tableName = nameString.content.text
            }
            else {
                diagnostics.append(
                    Diagnostic(
                        node: nameArg.expression,
                        id: "invalid-name-argument",
                        message: "The 'name' argument must be a simple string literal without interpolation. Remove the interpolation, or omit the argument to use the name of the struct."
                    )
                )
                self.tableName = structName
            }
        }
        else {
            self.tableName = structName
        }

        // Collect the properties from the struct definition.
        let properties = Self.collectProperties(declaration: declaration, diagnostics: &diagnostics)

        guard diagnostics.isEmpty else {
            // Report the diagnostics in source order, regardless of the order in which the
            // declarations were classified.
            let sorted = diagnostics.sorted {
                $0.node.positionAfterSkippingLeadingTrivia < $1.node.positionAfterSkippingLeadingTrivia
            }
            throw DiagnosticsError(diagnostics: sorted)
        }

        self.properties = properties
        self.optionalProperties = properties.map {
            MetaProperty(mutability: $0.mutability, name: $0.name, alias: $0.alias, optional: true, type: $0.type)
        }
        self.anonymousProperties = properties.map {
            MetaProperty(mutability: $0.mutability, name: $0.name, alias: $0.alias, optional: $0.optional, type: $0.type)
        }
        self.anonymousOptionalProperties = properties.map {
            MetaProperty(mutability: $0.mutability, name: $0.name, alias: $0.alias, optional: true, type: $0.type)
        }
        self.mutableProperties = properties.filter {
            $0.mutability == .mutable
        }
    }

    ///
    /// Collects the stored properties of the struct, mapping each one to a column.
    ///
    /// Every member of the struct is either mapped faithfully to a column, ignored because it can never
    /// be a column (methods, initializers, nested types, and static or computed properties), or reported
    /// as an error diagnostic located at the offending declaration. No property is ever silently dropped.
    ///
    private static func collectProperties(
        declaration: StructDeclSyntax,
        diagnostics: inout [Diagnostic]
    ) -> [MetaProperty] {
        var properties: [MetaProperty] = []
        for member in declaration.memberBlock.members {
            // Members which are not variable declarations (methods, initializers, nested types,
            // subscripts) are never columns.
            guard let variable = member.decl.as(VariableDeclSyntax.self) else {
                continue
            }
            properties.append(contentsOf: collectProperties(variable: variable, diagnostics: &diagnostics))
        }
        return properties
    }

    ///
    /// Maps a single variable declaration to zero or more columns, or appends an error diagnostic if the
    /// declaration cannot be mapped faithfully.
    ///
    private static func collectProperties(
        variable: VariableDeclSyntax,
        diagnostics: inout [Diagnostic]
    ) -> [MetaProperty] {

        func report(_ node: some SyntaxProtocol, id: String, _ message: String) {
            diagnostics.append(Diagnostic(node: node, id: id, message: message))
        }

        for modifier in variable.modifiers {
            switch modifier.name.text {
            case "static", "class":
                report(
                    modifier, id: "static-property",
                    "'\(modifier.name.text)' properties cannot be used as columns. Move the property to an extension of the type to exclude it from the generated columns."
                )
                return []
            case "lazy":
                report(
                    modifier, id: "lazy-property",
                    "'lazy' properties cannot be used as columns. Use a plain stored property instead."
                )
                return []
            case "weak", "unowned":
                report(
                    modifier, id: "reference-modifier",
                    "'\(modifier.name.text)' properties cannot be used as columns. Use a plain stored property instead."
                )
                return []
            default:
                // Access control and other modifiers do not affect column generation.
                break
            }
        }

        let mutability: MetaProperty.Mutability
        switch variable.bindingSpecifier.text {
        case "var":
            mutability = .mutable
        case "let":
            mutability = .immutable
        default:
            report(
                variable.bindingSpecifier, id: "binding-specifier",
                "'\(variable.bindingSpecifier.text)' properties cannot be used as columns. Use 'var' or 'let'."
            )
            return []
        }

        for binding in variable.bindings {
            if let accessorBlock = binding.accessorBlock, isComputed(accessorBlock) {
                report(
                    binding, id: "computed-property",
                    "Computed properties cannot be used as columns. Move the property to an extension of the type to exclude it from the generated columns."
                )
                return []
            }
        }

        // The type annotation carried backwards across the bindings of the declaration. A carried
        // annotation which was already reported as unsupported is marked invalid, so that the
        // bindings covered by it are skipped without emitting a misleading cascade of errors.
        enum CarriedType {
            case none
            case invalid
            case resolved(type: String, optional: Bool)
        }

        // Resolve the name and type of each binding. A type annotation applies to the contiguous
        // preceding bindings which have neither their own annotation nor an initial value
        // (e.g. in `let a, b: Int` both properties are of type Int), so the bindings are visited in
        // reverse order, carrying the most recently seen annotation backwards. Every invalid
        // binding is reported and skipped, so that a single declaration with several problems
        // produces a complete set of errors.
        var reversedProperties: [MetaProperty] = []
        var carriedType: CarriedType = .none
        for binding in variable.bindings.reversed() {

            guard let pattern = binding.pattern.as(IdentifierPatternSyntax.self) else {
                report(
                    binding.pattern, id: "unsupported-pattern",
                    "Pattern '\(binding.pattern.trimmedDescription)' cannot be used as a column. Declare each column as a separate property with its own name and type."
                )
                if let annotation = binding.typeAnnotation {
                    // Carry the annotation for the preceding bindings without reporting the type
                    // again. The pattern error already covers this binding.
                    if let resolved = resolveColumnType(annotation.type) {
                        carriedType = .resolved(type: resolved.type, optional: resolved.optional)
                    }
                    else {
                        carriedType = .invalid
                    }
                }
                continue
            }
            let name = pattern.identifier.text

            if let annotation = binding.typeAnnotation {
                if let resolved = resolveColumnType(annotation.type) {
                    carriedType = .resolved(type: resolved.type, optional: resolved.optional)
                }
                else {
                    report(
                        annotation.type, id: "unsupported-column-type",
                        "Type '\(annotation.type.trimmedDescription)' cannot be used as a column type."
                    )
                    carriedType = .invalid
                    continue
                }
            }

            let resolvedType: (type: String, optional: Bool)
            switch (binding.typeAnnotation, binding.initializer, carriedType) {
            case (.some, _, .resolved(let type, let optional)):
                resolvedType = (type, optional)
            case (nil, .some, _):
                report(
                    binding, id: "missing-type-annotation",
                    "Property '\(name)' needs an explicit type annotation to be used as a column. The type of the initial value cannot be inferred by the macro."
                )
                continue
            case (nil, nil, .resolved(let type, let optional)):
                resolvedType = (type, optional)
            case (nil, nil, .invalid):
                // The carried annotation was already reported as unsupported.
                continue
            case (nil, nil, .none):
                report(
                    binding, id: "missing-type-annotation",
                    "Property '\(name)' needs an explicit type annotation to be used as a column."
                )
                continue
            case (.some, _, .none), (.some, _, .invalid):
                // Unreachable: a resolved annotation always sets the carried type, and an
                // unsupported annotation skips the binding above.
                continue
            }

            if mutability == .immutable, binding.initializer != nil {
                report(
                    binding, id: "immutable-initial-value",
                    "A 'let' property with an initial value cannot be assigned by the generated initializer. Use 'var', or remove the initial value."
                )
                continue
            }

            // A property name may be escaped with backticks (e.g. to use a reserved word as a
            // name). The backticks are kept in the Swift name and stripped from the SQL name.
            let columnName: String
            if name.hasPrefix("`") && name.hasSuffix("`") && name.count > 2 {
                columnName = String(name.dropFirst().dropLast())
            }
            else {
                columnName = name
            }

            if reservedPropertyNames.contains(columnName) {
                report(
                    pattern, id: "reserved-property-name",
                    "Property name '\(columnName)' conflicts with a member generated by the macro. Rename the property."
                )
                continue
            }

            reversedProperties.append(
                MetaProperty(
                    mutability: mutability,
                    name: name,
                    alias: columnName,
                    optional: resolvedType.optional,
                    type: resolvedType.type
                )
            )
        }
        return reversedProperties.reversed()
    }

    ///
    /// Determines whether an accessor block belongs to a computed property. Stored properties may
    /// legitimately define `willSet` and `didSet` observers.
    ///
    private static func isComputed(_ accessorBlock: AccessorBlockSyntax) -> Bool {
        switch accessorBlock.accessors {
        case .getter:
            return true
        case .accessors(let accessors):
            return accessors.contains { accessor in
                switch accessor.accessorSpecifier.text {
                case "willSet", "didSet":
                    return false
                default:
                    return true
                }
            }
        }
    }

    ///
    /// Resolves a type annotation to a column type and optionality. Returns `nil` if the type cannot be
    /// used as a column type.
    ///
    private static func resolveColumnType(_ type: TypeSyntax) -> (type: String, optional: Bool)? {
        if let optionalType = type.as(OptionalTypeSyntax.self) {
            guard let wrapped = resolveColumnType(optionalType.wrappedType), !wrapped.optional else {
                return nil
            }
            return (wrapped.type, true)
        }
        if let identifierType = type.as(IdentifierTypeSyntax.self) {
            // Resolve the `Optional<T>` spelling to the same column type as `T?`.
            if identifierType.name.text == "Optional" {
                return resolveOptionalSugar(identifierType.genericArgumentClause)
            }
            // Keep generic arguments (e.g. `Array<Int>`) as part of the column type.
            return (identifierType.trimmedDescription, false)
        }
        if let memberType = type.as(MemberTypeSyntax.self) {
            // Resolve the module qualified `Swift.Optional<T>` spelling to the same column type
            // as `T?`.
            if
                memberType.name.text == "Optional",
                memberType.baseType.as(IdentifierTypeSyntax.self)?.name.text == "Swift"
            {
                return resolveOptionalSugar(memberType.genericArgumentClause)
            }
            return (memberType.trimmedDescription, false)
        }
        if type.is(ArrayTypeSyntax.self) || type.is(DictionaryTypeSyntax.self) {
            return (type.trimmedDescription, false)
        }
        return nil
    }

    ///
    /// Resolves the generic argument of an `Optional<T>` or `Swift.Optional<T>` spelling to the same
    /// column type as `T?`. Returns `nil` if the wrapped type cannot be used as a column type.
    ///
    private static func resolveOptionalSugar(
        _ genericArgumentClause: GenericArgumentClauseSyntax?
    ) -> (type: String, optional: Bool)? {
        guard
            let arguments = genericArgumentClause?.arguments,
            arguments.count == 1,
            let argument = arguments.first?.argument,
            let wrapped = resolveColumnType(argument),
            !wrapped.optional
        else {
            return nil
        }
        return (wrapped.type, true)
    }


    ///
    /// Creates an extension for the struct with the given conformance.
    ///
    /// - Parameter name: Name of the protocol.
    ///
    /// Example:
    ///
    /// Given the following struct:
    /// ```swift
    /// @SQLTable() struct Foo {
    /// }
    /// ```
    ///
    /// We can generate conformance for the `Bar` protocol:
    ///
    /// ```swift
    /// builder.makeConformanceExtension(name: "Bar")
    /// ```
    ///
    /// This will generate the following code:
    /// ```swift
    /// extension Foo: Bar {
    /// }
    /// ```
    ///
    func makeConformanceExtension(name: String) -> String {
        var context = SwiftSyntaxBuilder()
        context.block("extension \(structName): \(name)") { context in
            
        }
        return context.build()
    }

    
    // Build result-only meta data, used to select explicit columns without an underlying table.
    func makeMetaResultExtension(table: Bool) -> String {
        var context = SwiftSyntaxBuilder()
        context.block("extension \(structName): XLResult") { context in
            
            makeCommonMeta(context: &context, table: table)
        }
        return context.build()
    }
    
    // Build table meta data, used to select from concrete tables and views which are defined by the database schema.
    func makeMetaTableExtension() -> String {
        var context = SwiftSyntaxBuilder()

        context.block("extension \(structName): XLTable") { context in
            
            context.block("public static func sqlTableName() -> XLQualifiedTableName") { context in
                context.line("XLQualifiedTableName(name: XLName(\(quoted(tableName))))")
            }
            
            makeWriter(context: &context)

            context.block("public static func makeSQLTable(namespace: XLNamespace, dependency: XLTableDeclaration) -> MetaResult") { context in
                var parameters: [String] = []
                parameters.append("_namespace: namespace")
                parameters.append("_dependency: dependency")
                for property in properties {
                    parameters.append(property.name + ": " + property.makeInstance(kind: .reference, dependency: "dependency"))
                }
                context.block("MetaResult(" + parameters.joined(separator: ", ") + ")") { context in
                    context.declaration("\(structName)") { context in
                        for property in properties {
                            context.item { context in
                                context.line("\(property.name): try $0.column(\(property.makeInstance(kind: .reference, dependency: "dependency")), alias: \(quoted(property.alias)))")
                            }
                        }
                    }
                }
            }

            context.block("public static func makeSQLNamedResult(namespace: XLNamespace, dependency: XLNamedTableDeclaration) -> MetaNamedResult") { context in
                var parameters: [String] = []
                parameters.append("_namespace: namespace")
                parameters.append("_dependency: dependency")
                for property in properties {
                    parameters.append(property.name + ": " + property.makeInstance(kind: .reference, dependency: "dependency"))
                }
                context.block("MetaNamedResult(" + parameters.joined(separator: ", ") + ")") { context in
                    context.declaration("\(structName)") { context in
                        for property in properties {
                            context.item { context in
                                context.line("\(property.name): try $0.column(\(property.makeInstance(kind: .reference, dependency: "dependency")), alias: \(quoted(property.alias)))")
                            }
                        }
                    }
                }
            }
            
            context.block("public static func makeSQLNullableResult(namespace: XLNamespace, dependency: XLTableDeclaration) -> MetaNullableResult") { context in
                var parameters: [String] = []
                parameters.append("_namespace: namespace")
                parameters.append("_dependency: dependency")
                for property in optionalProperties {
                    parameters.append(property.name + ": " + property.makeInstance(kind: .reference, dependency: "dependency"))
                }
                context.block("return MetaNullableResult(" + parameters.joined(separator: ", ") + ")") { context in
                    context.declaration("Nullable") { context in
                        for property in optionalProperties {
                            context.item { context in
                                context.line("\(property.name): try $0.column(\(property.makeInstance(kind: .reference, dependency: "dependency")), alias: \(quoted(property.alias)))")
                            }
                        }
                    }
                }
            }
            
            context.block("public static func makeSQLNullableNamedResult(namespace: XLNamespace, dependency: XLNamedTableDeclaration) -> MetaNullableNamedResult") { context in
                var parameters: [String] = []
                parameters.append("_namespace: namespace")
                parameters.append("_dependency: dependency")
                for property in optionalProperties {
                    parameters.append(property.name + ": " + property.makeInstance(kind: .reference, dependency: "dependency"))
                }
                context.block("return MetaNullableNamedResult(" + parameters.joined(separator: ", ") + ")") { context in
                    context.declaration("Nullable") { context in
                        for property in optionalProperties {
                            context.item { context in
                                context.line("\(property.name): try $0.column(\(property.makeInstance(kind: .reference, dependency: "dependency")), alias: \(quoted(property.alias)))")
                            }
                        }
                    }
                }
            }
            
            makeCreate(context: &context)
        }
            
        return context.build()
    }
    
    private func makeWriter(context: inout SwiftSyntaxBuilder) {
        
        context.block("public struct MetaWritableTable: XLMetaWritableTable") { context in

            context.line("public typealias Row = \(structName)")
            context.line("public typealias Dependency = XLEncodable & XLColumnDependency")

            context.line("public let _table: any XLEncodable")

            context.line("public let _namespace: XLNamespace")
            context.line("private let _dependency: XLTableDeclaration")
            
            for property in properties {
                context.line(property.makeColumnPropertyDecl(kind: .reference))
            }

            context.block("public init(namespace: XLNamespace, dependency: XLTableDeclaration)") { context in
                context.line("_namespace = namespace")
                context.line("_dependency = dependency")
                context.line("_table = dependency")
                for property in properties {
                    context.line(property.name + " = " + property.makeInstance(kind: .reference, dependency: "dependency"))
                }
            }
            
            context.block("public func makeSQL(context: inout XLBuilder)") { context in

            }
        }

        context.block("public struct MetaInsert: XLMetaInsert") { context in
            
            context.line("public typealias Row = \(structName)")
            
            for property in properties {
                context.line("private let \(property.name): any XLExpression<\(property.qualifiedType)>")
            }
            
            // Discrete parameters.
            var parameters: [String] = []
            for property in properties {
                parameters.append("\(property.name): any XLExpression<\(property.qualifiedType)>")
            }
            context.block("public init(\(parameters.joined(separator: ", ")))") { context in
                for property in properties {
                    context.line("self.\(property.name) = \(property.name)")
                }
            }
            
            // Instance parameter.
            context.block("public init(_ instance: \(structName))") { context in
                for property in properties {
                    context.line("\(property.name) = XLTypeAffinityExpression<\(property.qualifiedType)>(expression: instance.\(property.name))")
                }
            }
            
            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                
                context.block("context.parenthesis") { context in
                    context.block("$0.list(separator: \",\")") { context in
                        for property in properties {
                            context.block("$0.listItem") { context in
                                context.line("$0.name(XLName(\"\(property.alias)\"))")
                            }
                        }
                    }
                }
                
                context.block("context.unaryPrefix(\"VALUES\")") { context in
                    context.block("$0.parenthesis") { context in
                        context.block("$0.list(separator: \",\")") { context in
                            for property in properties {
                                context.block("$0.listItem") { context in
                                    context.line("\(property.name).writeSQL(context: &$0)")
                                }
                            }
                        }
                    }
                }
            }
        }
            
        context.block("public struct MetaUpdate: XLMetaUpdate") { context in
            
            context.line("public typealias Row = \(structName)")
            
            for property in properties {
                context.line("public var \(property.name): Optional<any SwiftQL.XLExpression<\(property.qualifiedType)>>")
            }
            
            context.block("public init()") { context in
                for property in properties {
                    context.line("\(property.name) = nil")
                }
            }
            
            if !properties.isEmpty {
                var parameters: [String] = []
                for property in properties {
                    parameters.append("\(property.name): Optional<any XLExpression<\(property.qualifiedType)>> = nil")
                }
                context.block("public init(\(parameters.joined(separator: ", ")))") { context in
                    for property in properties {
                        context.line("self.\(property.name) = \(property.name)")
                    }
                }
            }
            
            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                context.block("context.unaryPrefix(\"SET\")") { context in
                    context.block("$0.list(separator: \",\")") { context in
                        for property in properties {
                            context.block("if let \(property.name)") { context in
                                context.block("$0.listItem") { context in
                                    context.block("$0.binaryOperator(\"=\", left: XLName(\"\(property.alias)\").makeSQL)") { context in
                                        context.line("\(property.name).writeSQL(context: &$0)")
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
               
        context.block("public struct UpdateRequest") { context in
            
            context.line("public typealias Row = \(structName)")
            
            for property in mutableProperties {
                context.line("public var \(property.name): Optional<\(property.type)>")
            }
            
            context.block("public init()") { context in
                for property in mutableProperties {
                    context.line("self.\(property.name) = nil")
                }
            }
            
            if !mutableProperties.isEmpty {
                var parameters: [String] = []
                for property in mutableProperties {
                    parameters.append("\(property.name): Optional<\(property.type)> = nil")
                }
                context.block("public init(\(parameters.joined(separator: ", ")))") { context in
                    for property in mutableProperties {
                        context.line("self.\(property.name) = \(property.name)")
                    }
                }
            }
            
            context.block("public func apply(to entity: Row) -> Row") { context in
                context.line("var output = entity")
                for property in mutableProperties {
                    context.block("if let value = \(property.name)") { context in
                        context.line("output.\(property.name) = value")
                    }
                }
                context.line("return output")
            }
            
            context.block("public func makeUpdate() -> MetaUpdate") { context in
                context.line("var output = MetaUpdate()")
                for property in mutableProperties {
                    context.block("if let value = \(property.name)") { context in
                        if property.optional {
                            context.line("output.\(property.name) = XLTypeAffinityExpression<\(property.qualifiedType)>(expression: value.toNullable())")
                        }
                        else {
                            context.line("output.\(property.name) = XLTypeAffinityExpression<\(property.qualifiedType)>(expression: value)")
                        }
                    }
                }
                context.line("return output")
            }
        }
        
        context.block("public static func makeSQLInsert(namespace: XLNamespace, dependency: XLTableDeclaration) -> MetaWritableTable") { context in
            context.line("MetaWritableTable(namespace: namespace, dependency: dependency)")
        }
        
        context.block("public static func makeSQLUpdate(namespace: XLNamespace, dependency: XLTableDeclaration) -> MetaWritableTable") { context in
            context.line("MetaWritableTable(namespace: namespace, dependency: dependency)")
        }
    }
    
    private func makeCreate(context: inout SwiftSyntaxBuilder) {
        
        context.block("public struct MetaCreate: XLMetaCreate") { context in
            
            context.line("public typealias Table = \(structName)")
            
            context.line("public let name: XLQualifiedTableName")
            
            context.block("public init(name: XLQualifiedTableName)") { context in
                context.line("self.name = name")
            }
            
            context.block("public func makeSQL(context: inout XLBuilder)") { context in

                context.block("context.createTable(self.name)") { context in
                    for property in properties {
                        context.line("$0.column(name: XLName(\"\(property.alias)\"), nullable: \(property.optional))")
                    }
                }
            }
        }
        
        context.block("public struct MetaCreateAs: XLMetaCreate") { context in
            
            context.line("public typealias Table = \(structName)")
            
            context.line("public let name: XLQualifiedTableName")
            
            context.block("public init(name: XLQualifiedTableName)") { context in
                context.line("self.name = name")
            }
            
            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                context.line("context.createTable(self.name)")
            }
        }
        
        context.block("public static func makeSQLCreate() -> MetaCreate") { context in
            context.line("MetaCreate(name: sqlTableName())")
        }
        
        context.block("public static func makeSQLCreateAs() -> MetaCreateAs") { context in
            context.line("MetaCreateAs(name: sqlTableName())")
        }
    }
    
    private func makeCommonMeta(context: inout SwiftSyntaxBuilder, table: Bool) {
        
        var properties: [MetaProperty]
        var optionalProperties: [MetaProperty]
        let conformances: [String] = ["XLRowReadable", "XLEncodable"]
        let columnKind: MetaProperty.ColumnKind
        if table {
            // Table
            columnKind = .reference
            properties = self.properties
            optionalProperties = self.optionalProperties
        }
        else {
            // Select result
            columnKind = .result
            properties = self.anonymousProperties
            optionalProperties = self.anonymousOptionalProperties

        }

        // Nullable
        context.block("public struct Nullable: XLMetaNullable") { context in
            
            context.line("public typealias Basis = \(structName)")
            
            for property in optionalProperties {
                context.line(property.makePropertyDecl())
            }
        }

        // MetaResult
        let metaResultConformances = (["XLMetaResult"] + conformances).joined(separator: ", ")
        context.block("public struct MetaResult: \(metaResultConformances)") { context in

            context.line("public typealias Row = \(structName)")
            context.line("public typealias RowIterator = (XLRowReader) throws -> \(structName)")
            context.line("public let _namespace: XLNamespace")
            context.line("public let _dependency: XLTableDeclaration")

            for property in properties {
                context.line(property.makeColumnPropertyDecl(kind: columnKind))
            }

            context.line("public let _iterator: RowIterator")

            context.block("public func readRow(reader: XLRowReader) throws -> \(structName)") { context in
                context.line("try _iterator(reader)")
            }

            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                context.line("_dependency.makeSQL(context: &context)")
            }
        }
        
        // MetaNamedResult
        let metaNamedResultConformances = (["XLMetaNamedResult"] + conformances).joined(separator: ", ")
        context.block("public struct MetaNamedResult: \(metaNamedResultConformances)") { context in

            context.line("public typealias Row = \(structName)")
            context.line("public typealias RowIterator = (XLRowReader) throws -> \(structName)")
            context.line("public let _namespace: XLNamespace")
            context.line("public let _dependency: XLNamedTableDeclaration")

            for property in properties {
                context.line(property.makeColumnPropertyDecl(kind: columnKind))
            }

            context.line("public let _iterator: RowIterator")

            context.block("public func readRow(reader: XLRowReader) throws -> \(structName)") { context in
                context.line("try _iterator(reader)")
            }

            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                context.line("_dependency.makeSQL(context: &context)")
            }
        }
        
        // MetaNullableResult
        let metaNullableResultConformances = (["XLMetaNullableResult"] + conformances).joined(separator: ", ")
        context.block("public struct MetaNullableResult: \(metaNullableResultConformances)") { context in

            context.line("public typealias Row = \(structName).Nullable")
            context.line("public typealias RowIterator = (XLRowReader) throws -> \(structName).Nullable")
            context.line("public let _namespace: XLNamespace")
            context.line("public let _dependency: XLTableDeclaration")

            for property in optionalProperties {
                context.line(property.makeColumnPropertyDecl(kind: columnKind))
            }

            context.line("public let _iterator: RowIterator")

            context.block("public func readRow(reader: XLRowReader) throws -> \(structName).Nullable") { context in
                context.line("try _iterator(reader)")
            }

            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                context.line("_dependency.makeSQL(context: &context)")
            }
        }
        
        // MetaNullableNamedResult
        let metaNullableNamedResultConformances = (["XLMetaNullableNamedResult"] + conformances).joined(separator: ", ")
        context.block("public struct MetaNullableNamedResult: \(metaNullableNamedResultConformances)") { context in

            context.line("public typealias Row = \(structName).Nullable")
            context.line("public typealias RowIterator = (XLRowReader) throws -> \(structName).Nullable")
            context.line("public let _namespace: XLNamespace")
            context.line("public let _dependency: XLNamedTableDeclaration")

            for property in optionalProperties {
                context.line(property.makeColumnPropertyDecl(kind: columnKind))
            }

            context.line("public let _iterator: RowIterator")

            context.block("public func readRow(reader: XLRowReader) throws -> \(structName).Nullable") { context in
                context.line("try _iterator(reader)")
            }

            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                context.line("_dependency.makeSQL(context: &context)")
            }
        }
        
        // MetaCommonTable
        context.block("public struct MetaCommonTable: XLMetaCommonTable") { context in
            
            context.line("public typealias Result = \(structName)")

            context.line("public let definition: XLCommonTableDependency")

            context.block("public init(commonTable: XLCommonTableDependency)") { context in
                context.line("self.definition = commonTable")
            }
        }

        // Reader
        context.block("public struct SQLReader: XLRowReadable") { context in

            context.line("public typealias Row = \(structName)")

            for property in properties {
                context.line("private let \(property.name): any SwiftQL.XLExpression<\(property.qualifiedType)>")
            }

            var parameters: [String] = []
            for property in properties {
                parameters.append("\(property.name): any SwiftQL.XLExpression<\(property.qualifiedType)>")
            }
            context.block("public init(\(parameters.joined(separator: ", ")))") { context in
                for property in properties {
                    context.line("self.\(property.name) = \(property.name)")
                }
            }

            context.block("public func readRow(reader: XLRowReader) throws -> \(structName)") { context in
                context.declaration("\(structName)") { context in
                    for property in properties {
                        context.item { context in
                            context.line("\(property.name): try reader.column(\(property.name), alias: \(quoted(property.alias)))")
                        }
                    }
                }
            }
        }
    
        // Static methods
        
        var columnParameters: [String] = []
        for property in properties {
            columnParameters.append("\(property.name): any SwiftQL.XLExpression<\(property.qualifiedType)>")
        }
        context.block("public static func columns(\(columnParameters.joined(separator: ", "))) -> MetaResult") { context in
            context.block("result") { context in
                context.declaration("SQLReader") { context in
                    for property in properties {
                        context.item { context in
                            context.line("\(property.name): \(property.name)")
                        }
                    }
                }
            }
        }
        
        context.block("public static func makeSQLCommonTable(namespace: XLNamespace, dependency: XLCommonTableDependency) -> MetaCommonTable") { context in
            context.line("MetaCommonTable(commonTable: dependency)")
        }

        context.block("public static func makeSQLAnonymousResult(namespace: XLNamespace, dependency: XLTableDeclaration, iterator: @escaping MetaRowIterator) -> MetaResult") { context in
            var parameters: [String] = []
            parameters.append("_namespace: namespace")
            parameters.append("_dependency: dependency")
            for property in anonymousProperties {
                parameters.append(property.name + ": " + property.makeInstance(kind: columnKind, dependency: "dependency"))
            }
            parameters.append("_iterator: iterator")
            context.line("return MetaResult(" + parameters.joined(separator: ", ") + ")")
        }

        context.block("public static func makeSQLAnonymousNamedResult(namespace: XLNamespace, dependency: XLNamedTableDeclaration, iterator: @escaping MetaRowIterator) -> MetaNamedResult") { context in
            var parameters: [String] = []
            parameters.append("_namespace: namespace")
            parameters.append("_dependency: dependency")
            for property in anonymousProperties {
                parameters.append(property.name + ": " + property.makeInstance(kind: columnKind, dependency: "dependency"))
            }
            parameters.append("_iterator: iterator")
            context.line("return MetaNamedResult(" + parameters.joined(separator: ", ") + ")")
        }
        
        context.block("public static func makeSQLAnonymousResult(namespace: XLNamespace, dependency: XLTableDeclaration) -> MetaResult") { context in
            var parameters: [String] = []
            parameters.append("_namespace: namespace")
            parameters.append("_dependency: dependency")
            for property in anonymousProperties {
                parameters.append(property.name + ": " + property.makeInstance(kind: columnKind, dependency: "dependency"))
            }
            context.block("return MetaResult(" + parameters.joined(separator: ", ") + ")") { context in
                context.declaration("\(structName)") { context in
                    for property in anonymousProperties {
                        context.item { context in
                            context.line("\(property.name): try $0.column(\(property.makeInstance(kind: .result, dependency: "dependency")), alias: \(quoted(property.alias)))")
                        }
                    }
                }
            }
        }
        
        context.block("public static func makeSQLAnonymousNamedResult(namespace: XLNamespace, dependency: XLNamedTableDeclaration) -> MetaNamedResult") { context in
            var parameters: [String] = []
            parameters.append("_namespace: namespace")
            parameters.append("_dependency: dependency")
            for property in anonymousProperties {
                parameters.append(property.name + ": " + property.makeInstance(kind: columnKind, dependency: "dependency"))
            }
            context.block("return MetaNamedResult(" + parameters.joined(separator: ", ") + ")") { context in
                context.declaration("\(structName)") { context in
                    for property in anonymousProperties {
                        context.item { context in
                            context.line("\(property.name): try $0.column(\(property.makeInstance(kind: .result, dependency: "dependency")), alias: \(quoted(property.alias)))")
                        }
                    }
                }
            }
        }
        
        context.block("public static func makeSQLAnonymousNullableResult(namespace: XLNamespace, dependency: XLTableDeclaration) -> MetaNullableResult") { context in
            var parameters: [String] = []
            parameters.append("_namespace: namespace")
            parameters.append("_dependency: dependency")
            for property in anonymousOptionalProperties {
                parameters.append(property.name + ": " + property.makeInstance(kind: columnKind, dependency: "dependency"))
            }
            context.block("return MetaNullableResult(" + parameters.joined(separator: ", ") + ")") { context in
                context.declaration("Nullable") { context in
                    for property in anonymousOptionalProperties {
                        context.item { context in
                            context.line("\(property.name): try $0.column(\(property.makeInstance(kind: .result, dependency: "dependency")), alias: \(quoted(property.alias)))")
                        }
                    }
                }
            }
        }
        
        context.block("public static func makeSQLAnonymousNullableNamedResult(namespace: XLNamespace, dependency: XLNamedTableDeclaration) -> MetaNullableNamedResult") { context in
            var parameters: [String] = []
            parameters.append("_namespace: namespace")
            parameters.append("_dependency: dependency")
            for property in anonymousOptionalProperties {
                parameters.append(property.name + ": " + property.makeInstance(kind: columnKind, dependency: "dependency"))
            }
            context.block("return MetaNullableNamedResult(" + parameters.joined(separator: ", ") + ")") { context in
                context.declaration("Nullable") { context in
                    for property in anonymousOptionalProperties {
                        context.item { context in
                            context.line("\(property.name): try $0.column(\(property.makeInstance(kind: .result, dependency: "dependency")), alias: \(quoted(property.alias)))")
                        }
                    }
                }
            }
        }    }
    
    func makeMemberwizeInitializer() -> String {
        var context = SwiftSyntaxBuilder()
        var parameters: [String] = []
        for property in properties {
            parameters.append("\(property.name): \(property.qualifiedType)")
        }
        context.block("public init(\(parameters.joined(separator: ", ")))") { context in
            for property in properties {
                context.line("self.\(property.name) = \(property.name)")
            }
        }
        return context.build()
    }

    ///
    /// Helper method used to surround a string with quote `"` characters.
    ///
    private func quoted(_ input: String) -> String {
        "\"\(input)\""
    }
}
