//
//  MetaBuilder.swift
//  
//
//  Created by Luke Van In on 2024/09/20.
//

import Foundation
import SwiftCompilerPlugin
import SwiftDiagnostics
import SwiftSyntax
import SwiftSyntaxBuilder
import SwiftSyntaxMacros


// MARK: - Builder


internal struct MetaProperty {
    
    enum ColumnKind {
        
        case reference
        
        case result
    }
    
    enum Mutability {
        
        case mutable
        
        case immutable
    }
    
    var mutability: Mutability
    var name: String
    var alias: String
    var optional: Bool
    var type: String

    /// The trimmed source text of the single argument passed to this property's `@SQLCodec(_:)`
    /// attribute (issue #66), or `nil` if the property declares no explicit codec selection. The
    /// macro never evaluates this expression -- it is spliced verbatim into generated code as a
    /// `.explicit(...)` codec-key reference, so it is resolved with the same visibility as the
    /// property's own declaration.
    var codecKeyExpression: String? = nil

    var qualifiedType: String {
        if optional {
            type + "?"
        }
        else {
            type
        }
    }
    
    func columnType(kind: ColumnKind) -> String {
        switch kind {
        case .reference:
            "XLColumnReference<\(qualifiedType)>"
        case .result:
            "XLColumnResult<\(qualifiedType)>"
        }
    }

    func makePropertyDecl() -> String {
        "public let \(name): \(qualifiedType)"
    }

    func makeColumnPropertyDecl(kind: ColumnKind) -> String {
        "public let \(name): \(columnType(kind: kind))"
    }
    
    func makeInstance(kind: ColumnKind, dependency: String) -> String {
        "\(columnType(kind: kind))(dependency: \(dependency), as: \"\(alias)\")"
    }
}


private struct GeneratedIdentifierAllocator {
    private var used: Set<String>

    init(used: Set<String>) {
        self.used = used
    }

    mutating func allocate(_ base: String) -> String {
        var candidate = base
        var suffix = 0
        while used.contains(candidate) {
            suffix += 1
            candidate = "\(base)_\(suffix)"
        }
        used.insert(candidate)
        return candidate
    }
}


// Removal of the legacy anonymous-result surface is tracked by
// https://github.com/lukevanin/swiftql/issues/90.

///
/// Generates code for `SQLTable` and `SQLResult` macros.
///
/// Used internally by SwiftQL to generate code for `SQLTable` and `SQLResult` macros.
///
internal struct MetaBuilder {
    
    /// Property names which collide with members generated by the macro (e.g. on `MetaResult` or
    /// `MetaWritableTable`), and would produce duplicate declarations in the expanded code.
    ///
    /// `staticResultField` is reserved unconditionally (issue #66 review feedback), even though
    /// the macro only emits a `staticResultField(_:...)` overload when some property on the type
    /// carries `@SQLCodec`. A property literally named `staticResultField` on a type that does
    /// use `@SQLCodec` would otherwise compile -- an instance stored property and a static
    /// function sharing one base name do not collide in Swift -- but the resulting
    /// `Type.staticResultField(...)` call site becomes genuinely confusing to read, and whether
    /// the macro emits the static overload at all depends on unrelated properties elsewhere in
    /// the same declaration. Reserving the name always gives one focused diagnostic instead of a
    /// conditional trap.
    private static let reservedPropertyNames: Set<String> = [
        "_table",
        "_namespace",
        "_dependency",
        "_iterator",
        "Row",
        "RowIterator",
        "Dependency",
        "Basis",
        "Nullable",
        "_swiftQLPropertyCodecKeys",
        "staticResultField",
    ]

    /// Name of the struct defined in the Swift source file.
    let structName: String
    
    /// Name of the SQL table which the struct refers to. SwiftQL uses the struct name for the table name
    /// unless the `name:` parameter is specified in the macro. Only applies to `SQLTable` macros.
    let tableName: String
    
    /// SwiftSyntax declaration of the struct.
    let declaration: StructDeclSyntax
    
    /// Non-optional properties defined on the struct. These properties correspond to table columns.
    let properties: [MetaProperty]
    
    /// Optional properties defined on the struct. These properties correspond to nullable table columns.
    let optionalProperties: [MetaProperty]
    
    /// Anonymous (unnamed) properties. Only applies to `SQLResult` macros.
    /// > TODO: Remove anonymous properties.
    let anonymousProperties: [MetaProperty]
    
    /// Optional anonymous  properties. Only applies to `SQLResult` macros.
    /// > TODO: Remove optional anonymous properties.
    let anonymousOptionalProperties: [MetaProperty]

    /// Mutable properties defined on the struct.
    let mutableProperties: [MetaProperty]

    /// Identifiers that generated method generics and locals must not shadow.
    ///
    /// Property types are included because a generated generic named like a
    /// concrete type would silently change the meaning of that type inside the
    /// generated signature. The nominal name is included because a generated
    /// local can otherwise shadow a return type with the same spelling.
    private var generatedIdentifierReservations: Set<String> {
        var identifiers: Set<String> = [structName]
        if let clause = declaration.genericParameterClause {
            identifiers.formUnion(clause.parameters.map { $0.name.text })
        }
        for property in properties {
            identifiers.insert(property.alias)
            identifiers.formUnion(Self.identifiers(in: property.type))
            identifiers.formUnion(Self.identifiers(in: property.qualifiedType))
        }
        return identifiers
    }

    private static func identifiers(in source: String) -> Set<String> {
        Set(
            source.split { character in
                character != "_"
                    && !character.isLetter
                    && !character.isNumber
            }.map(String.init)
        )
    }

    ///
    /// Convenience initializer used to initialise the builder with a `DeclGroupSyntax`.
    /// - throws: `SQLMacroError.unsupportedType` if the declaration is not a `StructDeclSyntax`
    ///
    init(node: AttributeSyntax, declaration: DeclGroupSyntax) throws {
        guard let declaration = declaration.as(StructDeclSyntax.self) else {
            throw SQLMacroError.unsupportedType
        }
        try self.init(node: node, declaration: declaration)
    }
    
    ///
    /// Initialises the builder with a node and a declaration.
    ///
    /// - Parameter node: Reference to the macro. E.g. `@SQLTable(name: "foo")`
    /// - Parameter declaration: Reference to the struct which the macro is defined on.
    ///
    /// The initializer collects the properties defined on the struct, to be used in generating the meta data
    /// for the table or result.
    ///
    init(node: AttributeSyntax, declaration: StructDeclSyntax) throws {
        self.structName = declaration.name.text
        self.declaration = declaration

        var diagnostics: [Diagnostic] = []

        // Use the name parameter from the macro if it is defined, otherwise
        // use the name of the struct for the table name.
        if
            case let .argumentList(arguments) = node.arguments,
            let nameArg = arguments.first(where: { $0.label?.text == "name" })
        {
            if
                let nameLiteral = nameArg.expression.as(StringLiteralExprSyntax.self),
                nameLiteral.segments.count == 1,
                case let .stringSegment(nameString)? = nameLiteral.segments.first
            {
                self.tableName = nameString.content.text
            }
            else {
                diagnostics.append(
                    Diagnostic(
                        node: nameArg.expression,
                        id: "invalid-name-argument",
                        message: "The 'name' argument must be a simple string literal without interpolation. Remove the interpolation, or omit the argument to use the name of the struct."
                    )
                )
                self.tableName = structName
            }
        }
        else {
            self.tableName = structName
        }

        // Collect the properties from the struct definition.
        let properties = Self.collectProperties(declaration: declaration, diagnostics: &diagnostics)

        guard diagnostics.isEmpty else {
            // Report the diagnostics in source order, regardless of the order in which the
            // declarations were classified.
            let sorted = diagnostics.sorted {
                $0.node.positionAfterSkippingLeadingTrivia < $1.node.positionAfterSkippingLeadingTrivia
            }
            throw DiagnosticsError(diagnostics: sorted)
        }

        self.properties = properties
        self.optionalProperties = properties.map {
            MetaProperty(mutability: $0.mutability, name: $0.name, alias: $0.alias, optional: true, type: $0.type)
        }
        self.anonymousProperties = properties.map {
            MetaProperty(mutability: $0.mutability, name: $0.name, alias: $0.alias, optional: $0.optional, type: $0.type)
        }
        self.anonymousOptionalProperties = properties.map {
            MetaProperty(mutability: $0.mutability, name: $0.name, alias: $0.alias, optional: true, type: $0.type)
        }
        self.mutableProperties = properties.filter {
            $0.mutability == .mutable
        }
    }

    ///
    /// Collects the stored properties of the struct, mapping each one to a column.
    ///
    /// Every member of the struct is either mapped faithfully to a column, ignored because it can never
    /// be a column (methods, initializers, and nested types), or reported as an error diagnostic located
    /// at the offending declaration (e.g. static, lazy, or computed properties). No property is ever
    /// silently dropped.
    ///
    private static func collectProperties(
        declaration: StructDeclSyntax,
        diagnostics: inout [Diagnostic]
    ) -> [MetaProperty] {
        var properties: [MetaProperty] = []
        for member in declaration.memberBlock.members {
            // Members which are not variable declarations (methods, initializers, nested types,
            // subscripts) are never columns.
            guard let variable = member.decl.as(VariableDeclSyntax.self) else {
                continue
            }
            properties.append(contentsOf: collectProperties(variable: variable, diagnostics: &diagnostics))
        }
        return properties
    }

    ///
    /// Maps a single variable declaration to zero or more columns, or appends an error diagnostic if the
    /// declaration cannot be mapped faithfully.
    ///
    private static func collectProperties(
        variable: VariableDeclSyntax,
        diagnostics: inout [Diagnostic]
    ) -> [MetaProperty] {

        func report(_ node: some SyntaxProtocol, id: String, _ message: String) {
            diagnostics.append(Diagnostic(node: node, id: id, message: message))
        }

        for modifier in variable.modifiers {
            switch modifier.name.text {
            case "static", "class":
                report(
                    modifier, id: "static-property",
                    "'\(modifier.name.text)' properties cannot be used as columns. Move the property to an extension of the type to exclude it from the generated columns."
                )
                return []
            case "lazy":
                report(
                    modifier, id: "lazy-property",
                    "'lazy' properties cannot be used as columns. Use a plain stored property instead."
                )
                return []
            case "weak", "unowned":
                report(
                    modifier, id: "reference-modifier",
                    "'\(modifier.name.text)' properties cannot be used as columns. Use a plain stored property instead."
                )
                return []
            default:
                // Access control and other modifiers do not affect column generation.
                break
            }
        }

        // Issue #66: a stored property may carry at most one `@SQLCodec(_:)` attribute,
        // selecting a named contextual value codec for that property alone. The attribute
        // applies to the variable declaration as a whole, so a declaration sharing one
        // annotation across several bindings (e.g. `@SQLCodec(x) var a, b: Int`) cannot
        // resolve which binding it names and is reported instead of guessed.
        let codecSelector = collectCodecSelector(
            attributes: variable.attributes,
            diagnostics: &diagnostics
        )
        if let codecSelector, variable.bindings.count > 1 {
            report(
                codecSelector.node, id: "ambiguous-codec-declaration-target",
                "'@SQLCodec' cannot be shared by several bindings in one declaration. Declare the annotated property in its own 'var'/'let' statement."
            )
        }

        let mutability: MetaProperty.Mutability
        switch variable.bindingSpecifier.text {
        case "var":
            mutability = .mutable
        case "let":
            mutability = .immutable
        default:
            report(
                variable.bindingSpecifier, id: "binding-specifier",
                "'\(variable.bindingSpecifier.text)' properties cannot be used as columns. Use 'var' or 'let'."
            )
            return []
        }

        // The type annotation carried backwards across the bindings of the declaration. A carried
        // annotation which was already reported as unsupported is marked invalid, so that the
        // bindings covered by it are skipped without emitting a misleading cascade of errors.
        enum CarriedType {
            case none
            case invalid
            case resolved(type: String, optional: Bool)
        }

        // Resolve the name and type of each binding. A type annotation applies to the contiguous
        // preceding bindings which have neither their own annotation nor an initial value
        // (e.g. in `let a, b: Int` both properties are of type Int), so the bindings are visited in
        // reverse order, carrying the most recently seen annotation backwards. Every invalid
        // binding is reported and skipped, so that a single declaration with several problems
        // produces a complete set of errors.
        var reversedProperties: [MetaProperty] = []
        var carriedType: CarriedType = .none

        // Carries the annotation of a binding which was already reported as invalid, without
        // reporting the annotation again, so that the bindings covered by it are still resolved.
        func carryAnnotation(of binding: PatternBindingSyntax) {
            guard let annotation = binding.typeAnnotation else {
                return
            }
            if let resolved = resolveColumnType(annotation.type) {
                carriedType = .resolved(type: resolved.type, optional: resolved.optional)
            }
            else {
                carriedType = .invalid
            }
        }

        for binding in variable.bindings.reversed() {

            if let accessorBlock = binding.accessorBlock, isComputed(accessorBlock) {
                report(
                    binding, id: "computed-property",
                    "Computed properties cannot be used as columns. Move the property to an extension of the type to exclude it from the generated columns."
                )
                carryAnnotation(of: binding)
                continue
            }

            guard let pattern = binding.pattern.as(IdentifierPatternSyntax.self) else {
                report(
                    binding.pattern, id: "unsupported-pattern",
                    "Pattern '\(binding.pattern.trimmedDescription)' cannot be used as a column. Declare each column as a separate property with its own name and type."
                )
                carryAnnotation(of: binding)
                continue
            }
            let name = pattern.identifier.text

            if let annotation = binding.typeAnnotation {
                if let resolved = resolveColumnType(annotation.type) {
                    carriedType = .resolved(type: resolved.type, optional: resolved.optional)
                }
                else {
                    report(
                        annotation.type, id: "unsupported-column-type",
                        "Type '\(annotation.type.trimmedDescription)' cannot be used as a column type. Use a named type that conforms to 'XLLiteral' for a scalar column, or a nested '@SQLTable'/'@SQLResult' type for a composite column selection."
                    )
                    carriedType = .invalid
                    continue
                }
            }

            let resolvedType: (type: String, optional: Bool)
            switch (binding.typeAnnotation, binding.initializer, carriedType) {
            case (.some, _, .resolved(let type, let optional)):
                resolvedType = (type, optional)
            case (nil, .some, _):
                report(
                    binding, id: "missing-type-annotation",
                    "Property '\(name)' needs an explicit type annotation to be used as a column. The type of the initial value cannot be inferred by the macro."
                )
                continue
            case (nil, nil, .resolved(let type, let optional)):
                resolvedType = (type, optional)
            case (nil, nil, .invalid):
                // The carried annotation was already reported as unsupported.
                continue
            case (nil, nil, .none):
                report(
                    binding, id: "missing-type-annotation",
                    "Property '\(name)' needs an explicit type annotation to be used as a column."
                )
                continue
            case (.some, _, .none), (.some, _, .invalid):
                // Unreachable: a resolved annotation always sets the carried type, and an
                // unsupported annotation skips the binding above.
                continue
            }

            if mutability == .immutable, binding.initializer != nil {
                report(
                    binding, id: "immutable-initial-value",
                    "A 'let' property with an initial value cannot be assigned by the generated initializer. Use 'var', or remove the initial value."
                )
                continue
            }

            // A property name may be escaped with backticks (e.g. to use a reserved word as a
            // name). The backticks are kept in the Swift name and stripped from the SQL name.
            let columnName: String
            if name.hasPrefix("`") && name.hasSuffix("`") && name.count > 2 {
                columnName = String(name.dropFirst().dropLast())
            }
            else {
                columnName = name
            }

            if reservedPropertyNames.contains(columnName) {
                report(
                    pattern, id: "reserved-property-name",
                    "Property name '\(columnName)' conflicts with a member generated by the macro. Rename the property."
                )
                continue
            }

            reversedProperties.append(
                MetaProperty(
                    mutability: mutability,
                    name: name,
                    alias: columnName,
                    optional: resolvedType.optional,
                    type: resolvedType.type,
                    codecKeyExpression: variable.bindings.count == 1
                        ? codecSelector?.expression
                        : nil
                )
            )
        }
        return reversedProperties.reversed()
    }

    /// Reads and validates every `@SQLCodec(_:)` attribute attached to one variable declaration
    /// (issue #66). `@SQLCodec` itself expands to nothing (see `SQLCodecMacro`); its role is
    /// metadata, resolved entirely here while `SQLTableMacro`/`SQLResultMacro` walk the
    /// property list. The Swift compiler already enforces the macro's own declared signature
    /// (`SQLCodec(_ key: XLValueCodecKey)`) as an ordinary call, so a wrong argument type or
    /// missing argument is diagnosed by the compiler itself before this ever runs; only shapes
    /// the compiler cannot see this early -- more than one selector on the same property, or a
    /// labeled/argument-count mismatch inside an already-valid call -- are reported here.
    private static func collectCodecSelector(
        attributes: AttributeListSyntax,
        diagnostics: inout [Diagnostic]
    ) -> (expression: String, node: AttributeSyntax)? {
        var selectors: [(expression: String, node: AttributeSyntax)] = []
        for element in attributes {
            guard case let .attribute(attribute) = element else {
                continue
            }
            guard attribute.attributeName.trimmedDescription == "SQLCodec" else {
                continue
            }
            guard
                case let .argumentList(arguments) = attribute.arguments,
                arguments.count == 1,
                let argument = arguments.first,
                argument.label == nil
            else {
                diagnostics.append(
                    Diagnostic(
                        node: attribute,
                        id: "invalid-codec-selector",
                        message: "'@SQLCodec' requires exactly one unlabeled argument naming a durable 'XLValueCodecKey'."
                    )
                )
                continue
            }
            selectors.append((argument.expression.trimmedDescription, attribute))
        }
        guard let first = selectors.first else {
            return nil
        }
        for duplicate in selectors.dropFirst() {
            diagnostics.append(
                Diagnostic(
                    node: duplicate.node,
                    id: "conflicting-codec-selector",
                    message: "Property has more than one '@SQLCodec' attribute. A property may select at most one explicit codec."
                )
            )
        }
        return first
    }

    ///
    /// Determines whether an accessor block belongs to a computed property. Stored properties may
    /// legitimately define `willSet` and `didSet` observers.
    ///
    private static func isComputed(_ accessorBlock: AccessorBlockSyntax) -> Bool {
        switch accessorBlock.accessors {
        case .getter:
            return true
        case .accessors(let accessors):
            return accessors.contains { accessor in
                switch accessor.accessorSpecifier.text {
                case "willSet", "didSet":
                    return false
                default:
                    return true
                }
            }
        }
    }

    ///
    /// Resolves a type annotation to a column type and optionality. Returns `nil` if the type cannot be
    /// used as a column type.
    ///
    private static func resolveColumnType(_ type: TypeSyntax) -> (type: String, optional: Bool)? {
        if let optionalType = type.as(OptionalTypeSyntax.self) {
            guard let wrapped = resolveColumnType(optionalType.wrappedType), !wrapped.optional else {
                return nil
            }
            return (wrapped.type, true)
        }
        if let identifierType = type.as(IdentifierTypeSyntax.self) {
            // Resolve the `Optional<T>` spelling to the same column type as `T?`.
            if identifierType.name.text == "Optional" {
                return resolveOptionalSugar(identifierType.genericArgumentClause)
            }
            // Keep generic arguments (e.g. `Array<Int>`) as part of the column type.
            return (identifierType.trimmedDescription, false)
        }
        if let memberType = type.as(MemberTypeSyntax.self) {
            // Resolve the module qualified `Swift.Optional<T>` spelling to the same column type
            // as `T?`.
            if
                memberType.name.text == "Optional",
                memberType.baseType.as(IdentifierTypeSyntax.self)?.name.text == "Swift"
            {
                return resolveOptionalSugar(memberType.genericArgumentClause)
            }
            return (memberType.trimmedDescription, false)
        }
        if type.is(ArrayTypeSyntax.self) || type.is(DictionaryTypeSyntax.self) {
            return (type.trimmedDescription, false)
        }
        return nil
    }

    ///
    /// Resolves the generic argument of an `Optional<T>` or `Swift.Optional<T>` spelling to the same
    /// column type as `T?`. Returns `nil` if the wrapped type cannot be used as a column type.
    ///
    private static func resolveOptionalSugar(
        _ genericArgumentClause: GenericArgumentClauseSyntax?
    ) -> (type: String, optional: Bool)? {
        guard
            let arguments = genericArgumentClause?.arguments,
            arguments.count == 1,
            let argument = arguments.first?.argument,
            let wrapped = resolveColumnType(argument),
            !wrapped.optional
        else {
            return nil
        }
        return (wrapped.type, true)
    }


    // Build result-only meta data, used to select explicit columns without an underlying table.
    func makeMetaResultExtension(table: Bool) -> String {
        var context = SwiftSyntaxBuilder()
        context.block("extension \(structName): XLResult") { context in
            
            makeCommonMeta(context: &context, table: table)
        }
        return context.build()
    }

    // Swift 5.9 does not reliably expose static members generated by an ExtensionMacro to
    // cross-file lookup (https://github.com/swiftlang/swift/issues/67989). Generate the public
    // projection factory through the MemberMacro role so `.columns(...)` remains available on
    // every supported compiler.
    func makeColumnsFunction() -> String {
        var context = SwiftSyntaxBuilder()
        var columnParameters: [String] = []
        for property in properties {
            columnParameters.append("\(property.name): any SwiftQL.XLExpression<\(property.qualifiedType)>")
        }
        context.block("public static func columns(\(columnParameters.joined(separator: ", "))) -> MetaResult") { context in
            context.block("return Self.makeSQLAnonymousResult", opening: "(", closing: ")") { context in
                context.line("namespace: XLNamespace.table(),")
                context.line("dependency: XLSelectResultDependency(),")
                context.block("iterator: Self.SQLReader", opening: "(", closing: ").readRow") { context in
                    for (index, property) in properties.enumerated() {
                        let suffix = index + 1 == properties.count ? "" : ","
                        context.line("\(property.name): \(property.name)\(suffix)")
                    }
                }
            }
        }
        return context.build()
    }

    // Generate the static layout factory as a nominal member for the same
    // Swift 5.9 cross-file lookup reason as `columns(...)`. The caller supplies
    // one `XLStaticRowFieldSource` value per property, allowing each use to
    // select its own expression and codec without constructing the model or
    // SQLReader.
    //
    // A property's argument is either an ordinary scalar field (any
    // `XLStaticSelectFieldProtocol` value, e.g. from `staticResultField` or
    // `.intrinsic`) or another generated type's own `staticRowLayout(using:...)`
    // result -- a nested `@SQLTable`/`@SQLResult` composite property. The macro
    // never has to tell those apart: both conform to `XLStaticRowFieldSource`,
    // and `grouped(at:alias:)` reports how many flat SQL slots it occupies
    // through its runtime `count`, so the generated code below only ever
    // accumulates a running slot offset -- it does not need to know any
    // property's arity at expansion time. A scalar property always
    // contributes exactly one slot; a nested composite property contributes
    // every one of its own flattened slots, re-aliased with its property name
    // as a prefix so the flattened SQL output columns stay unique.
    func makeStaticRowLayoutFunction() -> String {
        var context = SwiftSyntaxBuilder()
        var allocator = GeneratedIdentifierAllocator(
            used: generatedIdentifierReservations
        )
        let dialect = allocator.allocate("_SwiftQLStaticDialect")
        let fieldGroups = properties.indices.map { index in
            allocator.allocate("_swiftQLStaticField\(index)")
        }
        let offset = allocator.allocate("_swiftQLStaticOffset")
        let reader = allocator.allocate("_swiftQLStaticReader")
        let row = allocator.allocate("_swiftQLStaticRow")

        var parameters = ["using _: \(dialect).Type"]
        for property in properties {
            parameters.append(
                "\(property.name): some SwiftQL.XLStaticRowFieldSource<\(property.qualifiedType), \(dialect)>"
            )
        }

        // A running offset is reassigned only when a third or later property
        // needs it, so it is generated as an immutable binding otherwise --
        // avoiding an unused-mutation warning in the generated code.
        let offsetIsMutable = properties.count > 2

        context.block(
            "public static func staticRowLayout<\(dialect)>(\(parameters.joined(separator: ", "))) throws -> SwiftQL.XLStaticRowLayout<Self, \(dialect)> where \(dialect): SwiftQL.XLValueCodingDialect"
        ) { context in
            for (index, property) in properties.enumerated() {
                if index == 0 {
                    context.line(
                        "let \(fieldGroups[index]) = try \(property.name).grouped(at: 0, alias: \(quoted(property.alias)))"
                    )
                }
                else {
                    context.line(
                        "let \(fieldGroups[index]) = try \(property.name).grouped(at: \(offset), alias: \(quoted(property.alias)))"
                    )
                }
                if index < properties.count - 1 {
                    if index == 0 {
                        context.line("\(offsetIsMutable ? "var" : "let") \(offset) = \(fieldGroups[index]).count")
                    }
                    else {
                        context.line("\(offset) += \(fieldGroups[index]).count")
                    }
                }
            }

            context.block("return try SwiftQL.XLStaticRowLayout", opening: "(", closing: ")") { context in
                if fieldGroups.isEmpty {
                    context.line("fields: [],")
                }
                else {
                    // A single `.flatMap` over the per-property field arrays copies each
                    // element once; chaining `+` between them would instead recopy every
                    // earlier array on each concatenation (quadratic in property count).
                    context.line(
                        "fields: [" + fieldGroups.map { "\($0).fields" }.joined(separator: ", ") + "].flatMap { $0 },"
                    )
                }
                context.block(
                    "decode: { \(reader) in",
                    opening: "",
                    closing: "},"
                ) { context in
                    context.declaration("Self") { context in
                        for (index, property) in properties.enumerated() {
                            context.item { context in
                                context.line(
                                    "\(property.name): try \(fieldGroups[index]).read(from: \(reader))"
                                )
                            }
                        }
                    }
                }
                context.block(
                    "encode: { \(row) in",
                    opening: "",
                    closing: "}"
                ) { context in
                    if fieldGroups.isEmpty {
                        context.line("[]")
                    }
                    else {
                        let terms = zip(fieldGroups, properties).map { field, property in
                            "\(field).encode(\(row).\(property.name))"
                        }
                        if terms.count == 1 {
                            context.line("try \(terms[0])")
                        }
                        else {
                            // See the `fields:` array above: a single `.flatMap` over the
                            // per-property encoded arrays avoids the quadratic recopying
                            // that chaining `+` between them would cause.
                            context.line("try [\(terms.joined(separator: ", "))].flatMap { $0 }")
                        }
                    }
                }
            }
        }
        return context.build()
    }

    // Issue #66: stable, declaration-level codec metadata. Every generated type carries this
    // dictionary regardless of whether any property selects an explicit codec, so it is always a
    // reliable, directly inspectable surface (asserted by macro-expansion snapshot tests) rather
    // than a member that only sometimes exists. Only properties annotated with `@SQLCodec(_:)`
    // are present; every other property is left to the query/database-default precedence already
    // implemented by `XLValueCodingConfiguration`. Entries are keyed by SQL column alias, matching
    // the alias-based identity `XLStaticQueryResultSlot`/`XLValueCodingPath` already use elsewhere.
    //
    // Generated as a computed property, not a stored one: a generic `@SQLTable`/`@SQLResult`
    // type (e.g. `SQLScalarResult<T>`) cannot declare a `static let` -- Swift does not support
    // static stored properties on generic types -- so a computed property is the only form that
    // works uniformly for both generic and non-generic generated types.
    func makeCodecKeysDeclaration() -> String {
        var context = SwiftSyntaxBuilder()
        let entries = properties.compactMap { property -> (alias: String, expression: String)? in
            guard let codecKeyExpression = property.codecKeyExpression else {
                return nil
            }
            return (property.alias, codecKeyExpression)
        }
        context.block(
            "public static var _swiftQLPropertyCodecKeys: [String: SwiftQL.XLValueCodecKey]"
        ) { context in
            if entries.isEmpty {
                context.line("[:]")
            }
            else {
                context.block("[", opening: "", closing: "]") { context in
                    for entry in entries {
                        context.line("\(quoted(entry.alias)): \(entry.expression),")
                    }
                }
            }
        }
        return context.build()
    }

    // Issue #66: one generated static convenience per property carrying `@SQLCodec(_:)`, named
    // `staticResultField(<property>:...)` so a caller building a `staticRowLayout(using:...)`
    // argument for that property never repeats the codec key. The wrapper is metadata-only -- it
    // supplies `selection: .explicit(...)` and otherwise forwards straight to
    // `XLValueCodingConfiguration.staticResultField(...)`, so runtime resolution (unknown codec,
    // wrong Swift value type, wrong dialect) still runs through the existing precedence and
    // `XLValueCodecError`/`XLQueryCodecSelectionError` machinery. Because `XLStaticSelectField`
    // pairs `decode`/`encode` on one codec, this single generated factory backs projection
    // (`layout.decode`/`readRow`) and write paths (`layout.encode`) alike.
    func makeCodecResultFieldFunctions() -> [String] {
        var allocator = GeneratedIdentifierAllocator(
            used: generatedIdentifierReservations
        )
        var functions: [String] = []
        for property in properties {
            guard let codecKeyExpression = property.codecKeyExpression else {
                continue
            }
            let storage = allocator.allocate("_SwiftQLCodecStorage")
            let valueType = property.optional ? "\(property.type)?" : property.type
            let storageType = property.optional ? "\(storage)?" : storage
            var context = SwiftSyntaxBuilder()
            context.block(
                "public static func staticResultField<\(storage)>("
                    + "\(property.name) expression: any SwiftQL.XLEncodable, "
                    + "storedAs storageType: \(storageType).Type, "
                    + "identifiedBy identity: SwiftQL.XLQuerySlotIdentity, "
                    + "using dialect: SwiftQL.XLSQLiteDialect, "
                    + "context: SwiftQL.XLValueCodingContext? = nil, "
                    + "configuration: SwiftQL.XLValueCodingConfiguration"
                    + ") throws -> SwiftQL.XLStaticSelectField<\(valueType), \(storageType), SwiftQL.XLSQLiteDialect> "
                    + "where \(storage): SwiftQL.XLLiteral"
            ) { context in
                context.block(
                    "return try configuration.staticResultField",
                    opening: "(",
                    closing: ")"
                ) { context in
                    context.line("\(valueType).self,")
                    context.line("selecting: expression,")
                    context.line("storedAs: storageType,")
                    context.line("identifiedBy: identity,")
                    context.line("using: dialect,")
                    context.line("context: context,")
                    context.line("selection: .explicit(\(codecKeyExpression))")
                }
            }
            functions.append(context.build())
        }
        return functions
    }

    // Build table meta data, used to select from concrete tables and views which are defined by the database schema.
    func makeMetaTableExtension() -> String {
        var context = SwiftSyntaxBuilder()

        context.block("extension \(structName): XLTable") { context in
            
            context.block("public static func sqlTableName() -> XLQualifiedTableName") { context in
                context.line("XLQualifiedTableName(name: XLName(\(quoted(tableName))))")
            }
            
            makeWriter(context: &context)

            context.block("public static func makeSQLTable(namespace: XLNamespace, dependency: XLTableDeclaration) -> MetaResult") { context in
                var parameters: [String] = []
                parameters.append("_namespace: namespace")
                parameters.append("_dependency: dependency")
                for property in properties {
                    parameters.append(property.name + ": " + property.makeInstance(kind: .reference, dependency: "dependency"))
                }
                context.block(
                    "MetaResult(" + parameters.joined(separator: ", ") + ")",
                    opening: properties.isEmpty ? " { _ in" : " {"
                ) { context in
                    context.declaration("\(structName)") { context in
                        for property in properties {
                            context.item { context in
                                context.line("\(property.name): try $0.staticColumn(\(property.makeInstance(kind: .reference, dependency: "dependency")), alias: \(quoted(property.alias)))")
                            }
                        }
                    }
                }
            }

            context.block("public static func makeSQLNamedResult(namespace: XLNamespace, dependency: XLNamedTableDeclaration) -> MetaNamedResult") { context in
                var parameters: [String] = []
                parameters.append("_namespace: namespace")
                parameters.append("_dependency: dependency")
                for property in properties {
                    parameters.append(property.name + ": " + property.makeInstance(kind: .reference, dependency: "dependency"))
                }
                context.block(
                    "MetaNamedResult(" + parameters.joined(separator: ", ") + ")",
                    opening: properties.isEmpty ? " { _ in" : " {"
                ) { context in
                    context.declaration("\(structName)") { context in
                        for property in properties {
                            context.item { context in
                                context.line("\(property.name): try $0.staticColumn(\(property.makeInstance(kind: .reference, dependency: "dependency")), alias: \(quoted(property.alias)))")
                            }
                        }
                    }
                }
            }
            
            context.block("public static func makeSQLNullableResult(namespace: XLNamespace, dependency: XLTableDeclaration) -> MetaNullableResult") { context in
                var parameters: [String] = []
                parameters.append("_namespace: namespace")
                parameters.append("_dependency: dependency")
                for property in optionalProperties {
                    parameters.append(property.name + ": " + property.makeInstance(kind: .reference, dependency: "dependency"))
                }
                context.block(
                    "return MetaNullableResult(" + parameters.joined(separator: ", ") + ")",
                    opening: optionalProperties.isEmpty ? " { _ in" : " {"
                ) { context in
                    context.declaration("Nullable") { context in
                        for property in optionalProperties {
                            context.item { context in
                                context.line("\(property.name): try $0.staticColumn(\(property.makeInstance(kind: .reference, dependency: "dependency")), alias: \(quoted(property.alias)))")
                            }
                        }
                    }
                }
            }
            
            context.block("public static func makeSQLNullableNamedResult(namespace: XLNamespace, dependency: XLNamedTableDeclaration) -> MetaNullableNamedResult") { context in
                var parameters: [String] = []
                parameters.append("_namespace: namespace")
                parameters.append("_dependency: dependency")
                for property in optionalProperties {
                    parameters.append(property.name + ": " + property.makeInstance(kind: .reference, dependency: "dependency"))
                }
                context.block(
                    "return MetaNullableNamedResult(" + parameters.joined(separator: ", ") + ")",
                    opening: optionalProperties.isEmpty ? " { _ in" : " {"
                ) { context in
                    context.declaration("Nullable") { context in
                        for property in optionalProperties {
                            context.item { context in
                                context.line("\(property.name): try $0.staticColumn(\(property.makeInstance(kind: .reference, dependency: "dependency")), alias: \(quoted(property.alias)))")
                            }
                        }
                    }
                }
            }
            
            makeCreate(context: &context)
        }
            
        return context.build()
    }
    
    private func makeWriter(context: inout SwiftSyntaxBuilder) {
        
        context.block("public struct MetaWritableTable: XLMetaWritableTable") { context in

            context.line("public typealias Row = \(structName)")
            context.line("public typealias Dependency = XLEncodable & XLColumnDependency")

            context.line("public let _table: any XLEncodable")

            context.line("public let _namespace: XLNamespace")
            context.line("private let _dependency: XLTableDeclaration")
            
            for property in properties {
                context.line(property.makeColumnPropertyDecl(kind: .reference))
            }

            context.block("public init(namespace: XLNamespace, dependency: XLTableDeclaration)") { context in
                context.line("_namespace = namespace")
                context.line("_dependency = dependency")
                context.line("_table = dependency")
                for property in properties {
                    context.line(property.name + " = " + property.makeInstance(kind: .reference, dependency: "dependency"))
                }
            }
            
            context.block("public func makeSQL(context: inout XLBuilder)") { context in

            }
        }

        context.block("public struct MetaInsert: XLMetaInsert") { context in
            
            context.line("public typealias Row = \(structName)")
            
            for property in properties {
                context.line("private let \(property.name): any XLExpression<\(property.qualifiedType)>")
            }
            
            // Discrete parameters.
            var parameters: [String] = []
            for property in properties {
                parameters.append("\(property.name): any XLExpression<\(property.qualifiedType)>")
            }
            context.block("public init(\(parameters.joined(separator: ", ")))") { context in
                for property in properties {
                    context.line("self.\(property.name) = \(property.name)")
                }
            }
            
            // Instance parameter.
            context.block("public init(_ instance: \(structName))") { context in
                for property in properties {
                    context.line("\(property.name) = SwiftQL._xlLegacyValueExpression(instance.\(property.name))")
                }
            }
            
            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                
                context.block("context.parenthesis") { context in
                    context.block("$0.list(separator: \",\")") { context in
                        for property in properties {
                            context.block("$0.listItem") { context in
                                context.line("$0.name(XLName(\"\(property.alias)\"))")
                            }
                        }
                    }
                }
                
                context.block("context.unaryPrefix(\"VALUES\")") { context in
                    context.block("$0.parenthesis") { context in
                        context.block("$0.list(separator: \",\")") { context in
                            for property in properties {
                                context.block("$0.listItem") { context in
                                    context.line("\(property.name).writeSQL(context: &$0)")
                                }
                            }
                        }
                    }
                }
            }
        }
            
        context.block("public struct MetaUpdate: XLMetaUpdate") { context in
            
            context.line("public typealias Row = \(structName)")
            
            for property in properties {
                context.line("public var \(property.name): Optional<any SwiftQL.XLExpression<\(property.qualifiedType)>>")
            }
            
            context.block("public init()") { context in
                for property in properties {
                    context.line("\(property.name) = nil")
                }
            }
            
            if !properties.isEmpty {
                var parameters: [String] = []
                for property in properties {
                    parameters.append("\(property.name): Optional<any XLExpression<\(property.qualifiedType)>> = nil")
                }
                context.block("public init(\(parameters.joined(separator: ", ")))") { context in
                    for property in properties {
                        context.line("self.\(property.name) = \(property.name)")
                    }
                }
            }
            
            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                context.block("context.unaryPrefix(\"SET\")") { context in
                    context.block("$0.list(separator: \",\")") { context in
                        for property in properties {
                            context.block("if let \(property.name)") { context in
                                context.block("$0.listItem") { context in
                                    context.block("$0.binaryOperator(\"=\", left: XLName(\"\(property.alias)\").makeSQL)") { context in
                                        context.line("\(property.name).writeSQL(context: &$0)")
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
               
        context.block("public struct UpdateRequest") { context in
            
            context.line("public typealias Row = \(structName)")
            
            for property in mutableProperties {
                context.line("public var \(property.name): Optional<\(property.type)>")
            }
            
            context.block("public init()") { context in
                for property in mutableProperties {
                    context.line("self.\(property.name) = nil")
                }
            }
            
            if !mutableProperties.isEmpty {
                var parameters: [String] = []
                for property in mutableProperties {
                    parameters.append("\(property.name): Optional<\(property.type)> = nil")
                }
                context.block("public init(\(parameters.joined(separator: ", ")))") { context in
                    for property in mutableProperties {
                        context.line("self.\(property.name) = \(property.name)")
                    }
                }
            }
            
            context.block("public func apply(to entity: Row) -> Row") { context in
                if mutableProperties.isEmpty {
                    context.line("return entity")
                }
                else {
                    context.line("var output = entity")
                    for property in mutableProperties {
                        context.block("if let value = \(property.name)") { context in
                            context.line("output.\(property.name) = value")
                        }
                    }
                    context.line("return output")
                }
            }
            
            context.block("public func makeUpdate() -> MetaUpdate") { context in
                if mutableProperties.isEmpty {
                    context.line("return MetaUpdate()")
                }
                else {
                    context.line("var output = MetaUpdate()")
                    for property in mutableProperties {
                        context.block("if let value = \(property.name)") { context in
                            if property.optional {
                                context.line("output.\(property.name) = SwiftQL._xlLegacyValueExpression(value).toNullable()")
                            }
                            else {
                                context.line("output.\(property.name) = SwiftQL._xlLegacyValueExpression(value)")
                            }
                        }
                    }
                    context.line("return output")
                }
            }
        }
        
        context.block("public static func makeSQLInsert(namespace: XLNamespace, dependency: XLTableDeclaration) -> MetaWritableTable") { context in
            context.line("MetaWritableTable(namespace: namespace, dependency: dependency)")
        }
        
        context.block("public static func makeSQLUpdate(namespace: XLNamespace, dependency: XLTableDeclaration) -> MetaWritableTable") { context in
            context.line("MetaWritableTable(namespace: namespace, dependency: dependency)")
        }
    }
    
    private func makeCreate(context: inout SwiftSyntaxBuilder) {
        
        context.block("public struct MetaCreate: XLMetaCreate") { context in
            
            context.line("public typealias Table = \(structName)")
            
            context.line("public let name: XLQualifiedTableName")
            
            context.block("public init(name: XLQualifiedTableName)") { context in
                context.line("self.name = name")
            }
            
            context.block("public func makeSQL(context: inout XLBuilder)") { context in

                context.block("context.createTable(self.name)") { context in
                    for property in properties {
                        context.line("$0.column(name: XLName(\"\(property.alias)\"), nullable: \(property.optional))")
                    }
                }
            }
        }
        
        context.block("public struct MetaCreateAs: XLMetaCreate") { context in
            
            context.line("public typealias Table = \(structName)")
            
            context.line("public let name: XLQualifiedTableName")
            
            context.block("public init(name: XLQualifiedTableName)") { context in
                context.line("self.name = name")
            }
            
            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                context.line("context.createTable(self.name)")
            }
        }
        
        context.block("public static func makeSQLCreate() -> MetaCreate") { context in
            context.line("MetaCreate(name: sqlTableName())")
        }
        
        context.block("public static func makeSQLCreateAs() -> MetaCreateAs") { context in
            context.line("MetaCreateAs(name: sqlTableName())")
        }
    }
    
    private func makeCommonMeta(context: inout SwiftSyntaxBuilder, table: Bool) {
        
        var properties: [MetaProperty]
        var optionalProperties: [MetaProperty]
        let conformances: [String] = ["XLRowReadable", "XLEncodable"]
        let columnKind: MetaProperty.ColumnKind
        if table {
            // Table
            columnKind = .reference
            properties = self.properties
            optionalProperties = self.optionalProperties
        }
        else {
            // Select result
            columnKind = .result
            properties = self.anonymousProperties
            optionalProperties = self.anonymousOptionalProperties

        }

        // Nullable
        context.block("public struct Nullable: XLMetaNullable") { context in
            
            context.line("public typealias Basis = \(structName)")
            
            for property in optionalProperties {
                context.line(property.makePropertyDecl())
            }
        }

        // MetaResult
        let metaResultConformances = (["XLMetaResult"] + conformances).joined(separator: ", ")
        context.block("public struct MetaResult: \(metaResultConformances)") { context in

            context.line("public typealias Row = \(structName)")
            context.line("public typealias RowIterator = (XLRowReader) throws -> \(structName)")
            context.line("public let _namespace: XLNamespace")
            context.line("public let _dependency: XLTableDeclaration")

            for property in properties {
                context.line(property.makeColumnPropertyDecl(kind: columnKind))
            }

            context.line("public let _iterator: RowIterator")

            context.block("public func readRow(reader: XLRowReader) throws -> \(structName)") { context in
                context.line("try _iterator(reader)")
            }

            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                context.line("_dependency.makeSQL(context: &context)")
            }
        }
        
        // MetaNamedResult
        let metaNamedResultConformances = (["XLMetaNamedResult"] + conformances).joined(separator: ", ")
        context.block("public struct MetaNamedResult: \(metaNamedResultConformances)") { context in

            context.line("public typealias Row = \(structName)")
            context.line("public typealias RowIterator = (XLRowReader) throws -> \(structName)")
            context.line("public let _namespace: XLNamespace")
            context.line("public let _dependency: XLNamedTableDeclaration")

            for property in properties {
                context.line(property.makeColumnPropertyDecl(kind: columnKind))
            }

            context.line("public let _iterator: RowIterator")

            context.block("public func readRow(reader: XLRowReader) throws -> \(structName)") { context in
                context.line("try _iterator(reader)")
            }

            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                context.line("_dependency.makeSQL(context: &context)")
            }
        }
        
        // MetaNullableResult
        let metaNullableResultConformances = (["XLMetaNullableResult"] + conformances).joined(separator: ", ")
        context.block("public struct MetaNullableResult: \(metaNullableResultConformances)") { context in

            context.line("public typealias Row = \(structName).Nullable")
            context.line("public typealias RowIterator = (XLRowReader) throws -> \(structName).Nullable")
            context.line("public let _namespace: XLNamespace")
            context.line("public let _dependency: XLTableDeclaration")

            for property in optionalProperties {
                context.line(property.makeColumnPropertyDecl(kind: columnKind))
            }

            context.line("public let _iterator: RowIterator")

            context.block("public func readRow(reader: XLRowReader) throws -> \(structName).Nullable") { context in
                context.line("try _iterator(reader)")
            }

            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                context.line("_dependency.makeSQL(context: &context)")
            }
        }
        
        // MetaNullableNamedResult
        let metaNullableNamedResultConformances = (["XLMetaNullableNamedResult"] + conformances).joined(separator: ", ")
        context.block("public struct MetaNullableNamedResult: \(metaNullableNamedResultConformances)") { context in

            context.line("public typealias Row = \(structName).Nullable")
            context.line("public typealias RowIterator = (XLRowReader) throws -> \(structName).Nullable")
            context.line("public let _namespace: XLNamespace")
            context.line("public let _dependency: XLNamedTableDeclaration")

            for property in optionalProperties {
                context.line(property.makeColumnPropertyDecl(kind: columnKind))
            }

            context.line("public let _iterator: RowIterator")

            context.block("public func readRow(reader: XLRowReader) throws -> \(structName).Nullable") { context in
                context.line("try _iterator(reader)")
            }

            context.block("public func makeSQL(context: inout XLBuilder)") { context in
                context.line("_dependency.makeSQL(context: &context)")
            }
        }
        
        // MetaCommonTable
        context.block("public struct MetaCommonTable: XLMetaCommonTable") { context in
            
            context.line("public typealias Result = \(structName)")

            context.line("public let definition: XLCommonTableDependency")

            context.block("public init(commonTable: XLCommonTableDependency)") { context in
                context.line("self.definition = commonTable")
            }
        }

        // Reader
        var readerAllocator = GeneratedIdentifierAllocator(
            used: generatedIdentifierReservations
        )
        let rowReader = readerAllocator.allocate("_swiftQLRowReader")
        context.block("public struct SQLReader: XLRowReadable") { context in

            context.line("public typealias Row = \(structName)")

            for property in properties {
                context.line("private let \(property.name): any SwiftQL.XLExpression<\(property.qualifiedType)>")
            }

            var parameters: [String] = []
            for property in properties {
                parameters.append("\(property.name): any SwiftQL.XLExpression<\(property.qualifiedType)>")
            }
            context.block("public init(\(parameters.joined(separator: ", ")))") { context in
                for property in properties {
                    context.line("self.\(property.name) = \(property.name)")
                }
            }

            context.block("public func readRow(reader \(rowReader): XLRowReader) throws -> \(structName)") { context in
                context.declaration("\(structName)") { context in
                    for property in properties {
                        context.item { context in
                            context.line("\(property.name): try \(rowReader).staticColumn(\(property.name), alias: \(quoted(property.alias)))")
                        }
                    }
                }
            }
        }
    
        // Static methods
        
        context.block("public static func makeSQLCommonTable(namespace: XLNamespace, dependency: XLCommonTableDependency) -> MetaCommonTable") { context in
            context.line("MetaCommonTable(commonTable: dependency)")
        }

        context.block("public static func makeSQLAnonymousResult(namespace: XLNamespace, dependency: XLTableDeclaration, iterator: @escaping MetaRowIterator) -> MetaResult") { context in
            var parameters: [String] = []
            parameters.append("_namespace: namespace")
            parameters.append("_dependency: dependency")
            for property in anonymousProperties {
                parameters.append(property.name + ": " + property.makeInstance(kind: columnKind, dependency: "dependency"))
            }
            parameters.append("_iterator: iterator")
            context.line("return MetaResult(" + parameters.joined(separator: ", ") + ")")
        }

        context.block("public static func makeSQLAnonymousNamedResult(namespace: XLNamespace, dependency: XLNamedTableDeclaration, iterator: @escaping MetaRowIterator) -> MetaNamedResult") { context in
            var parameters: [String] = []
            parameters.append("_namespace: namespace")
            parameters.append("_dependency: dependency")
            for property in anonymousProperties {
                parameters.append(property.name + ": " + property.makeInstance(kind: columnKind, dependency: "dependency"))
            }
            parameters.append("_iterator: iterator")
            context.line("return MetaNamedResult(" + parameters.joined(separator: ", ") + ")")
        }
        
        context.block("public static func makeSQLAnonymousResult(namespace: XLNamespace, dependency: XLTableDeclaration) -> MetaResult") { context in
            var parameters: [String] = []
            parameters.append("_namespace: namespace")
            parameters.append("_dependency: dependency")
            for property in anonymousProperties {
                parameters.append(property.name + ": " + property.makeInstance(kind: columnKind, dependency: "dependency"))
            }
            context.block(
                "return MetaResult(" + parameters.joined(separator: ", ") + ")",
                opening: anonymousProperties.isEmpty ? " { _ in" : " {"
            ) { context in
                context.declaration("\(structName)") { context in
                    for property in anonymousProperties {
                        context.item { context in
                            context.line("\(property.name): try $0.staticColumn(\(property.makeInstance(kind: .result, dependency: "dependency")), alias: \(quoted(property.alias)))")
                        }
                    }
                }
            }
        }
        
        context.block("public static func makeSQLAnonymousNamedResult(namespace: XLNamespace, dependency: XLNamedTableDeclaration) -> MetaNamedResult") { context in
            var parameters: [String] = []
            parameters.append("_namespace: namespace")
            parameters.append("_dependency: dependency")
            for property in anonymousProperties {
                parameters.append(property.name + ": " + property.makeInstance(kind: columnKind, dependency: "dependency"))
            }
            context.block(
                "return MetaNamedResult(" + parameters.joined(separator: ", ") + ")",
                opening: anonymousProperties.isEmpty ? " { _ in" : " {"
            ) { context in
                context.declaration("\(structName)") { context in
                    for property in anonymousProperties {
                        context.item { context in
                            context.line("\(property.name): try $0.staticColumn(\(property.makeInstance(kind: .result, dependency: "dependency")), alias: \(quoted(property.alias)))")
                        }
                    }
                }
            }
        }
        
        context.block("public static func makeSQLAnonymousNullableResult(namespace: XLNamespace, dependency: XLTableDeclaration) -> MetaNullableResult") { context in
            var parameters: [String] = []
            parameters.append("_namespace: namespace")
            parameters.append("_dependency: dependency")
            for property in anonymousOptionalProperties {
                parameters.append(property.name + ": " + property.makeInstance(kind: columnKind, dependency: "dependency"))
            }
            context.block(
                "return MetaNullableResult(" + parameters.joined(separator: ", ") + ")",
                opening: anonymousOptionalProperties.isEmpty ? " { _ in" : " {"
            ) { context in
                context.declaration("Nullable") { context in
                    for property in anonymousOptionalProperties {
                        context.item { context in
                            context.line("\(property.name): try $0.staticColumn(\(property.makeInstance(kind: .result, dependency: "dependency")), alias: \(quoted(property.alias)))")
                        }
                    }
                }
            }
        }
        
        context.block("public static func makeSQLAnonymousNullableNamedResult(namespace: XLNamespace, dependency: XLNamedTableDeclaration) -> MetaNullableNamedResult") { context in
            var parameters: [String] = []
            parameters.append("_namespace: namespace")
            parameters.append("_dependency: dependency")
            for property in anonymousOptionalProperties {
                parameters.append(property.name + ": " + property.makeInstance(kind: columnKind, dependency: "dependency"))
            }
            context.block(
                "return MetaNullableNamedResult(" + parameters.joined(separator: ", ") + ")",
                opening: anonymousOptionalProperties.isEmpty ? " { _ in" : " {"
            ) { context in
                context.declaration("Nullable") { context in
                    for property in anonymousOptionalProperties {
                        context.item { context in
                            context.line("\(property.name): try $0.staticColumn(\(property.makeInstance(kind: .result, dependency: "dependency")), alias: \(quoted(property.alias)))")
                        }
                    }
                }
            }
        }    }
    
    func makeMemberwizeInitializer() -> String {
        var context = SwiftSyntaxBuilder()
        var parameters: [String] = []
        for property in properties {
            parameters.append("\(property.name): \(property.qualifiedType)")
        }
        context.block("public init(\(parameters.joined(separator: ", ")))") { context in
            for property in properties {
                context.line("self.\(property.name) = \(property.name)")
            }
        }
        return context.build()
    }

    ///
    /// Helper method used to surround a string with quote `"` characters.
    ///
    private func quoted(_ input: String) -> String {
        "\"\(input)\""
    }
}
