//
//  DeclaredQueryRegistryRenderer.swift
//  SwiftQLDeclaredQueryDiscovery
//
//  Issue #659: renders the Swift source of a target's declared-query
//  registry from a scan of its declarations.
//

import Foundation


public enum DeclaredQueryRegistryRenderer {

    ///
    /// The registry's type name for a target: the target name as an upper
    /// camel case identifier, followed by `DeclaredQueries`.
    ///
    public static func typeName(forTarget target: String) -> String {
        var result = ""
        var capitalizesNext = true
        for character in target {
            guard character.isLetter || character.isNumber || character == "_" else {
                capitalizesNext = true
                continue
            }
            if capitalizesNext {
                result += String(character).uppercased()
            }
            else {
                result.append(character)
            }
            capitalizesNext = false
        }
        if result.isEmpty {
            result = "Target"
        }
        if let first = result.first, first.isNumber {
            result = "_" + result
        }
        return result + "DeclaredQueries"
    }

    ///
    /// The registry source for `targetName`.
    ///
    /// The registry is a public enum whose one method takes database
    /// instances as `Any`, so its public signature names no type the target
    /// might keep internal. For each database type that declares queries, it
    /// reads every declaration's generated member from the first matching
    /// instance, and throws when no instance of that type was passed.
    ///
    public static func render(targetName: String, scan: DeclaredQueryScan) -> String {
        let registry = typeName(forTarget: targetName)
        var order: [String] = []
        var byType: [String: [DeclaredQueryDeclaration]] = [:]
        for declaration in scan.declarations {
            if byType[declaration.databaseType] == nil {
                order.append(declaration.databaseType)
            }
            byType[declaration.databaseType, default: []].append(declaration)
        }

        var lines: [String] = []
        lines.append("// Generated by SwiftQLDeclaredQueryRegistryPlugin from the @SQLQuery and")
        lines.append("// @SQLQueries declarations in target '\(targetName)'. Do not edit.")
        for skipped in scan.skipped {
            let fileName = URL(fileURLWithPath: skipped.file).lastPathComponent
            lines.append("//")
            lines.append("// Skipped \(fileName):\(skipped.line): \(skipped.reason)")
        }
        lines.append("")
        var imports = scan.imports
        if !imports.contains("SwiftQL") {
            imports.append("SwiftQL")
        }
        for module in imports.sorted() {
            lines.append("import \(module)")
        }
        lines.append("")
        lines.append("/// Every declared query in target '\(targetName)' that generated code can reach.")
        lines.append("public enum \(registry) {")
        lines.append("")
        lines.append("    /// The database types that declare queries, as the declarations spell them.")
        if order.isEmpty {
            lines.append("    public static let databaseTypeNames: [String] = []")
        }
        else {
            lines.append("    public static let databaseTypeNames: [String] = [")
            for type in order {
                lines.append("        \"\(type)\",")
            }
            lines.append("    ]")
        }
        lines.append("")
        lines.append("    /// The declared queries of the database instances in `databases`.")
        lines.append("    ///")
        lines.append("    /// - Throws: `XLDeclaredQueryError.missingDatabaseInstance` when")
        lines.append("    ///   `databases` holds no instance of a type that declares queries.")
        lines.append("    public static func queries(for databases: [Any]) throws -> [XLDeclaredQuery] {")
        if order.isEmpty {
            lines.append("        []")
            lines.append("    }")
            lines.append("}")
            return lines.joined(separator: "\n") + "\n"
        }
        lines.append("        var queries: [XLDeclaredQuery] = []")
        for (offset, type) in order.enumerated() {
            let declarations = byType[type] ?? []
            let needsVariable = declarations.contains { declaration in
                if case .peer(_, true) = declaration.form {
                    return true
                }
                return false
            }
            lines.append("")
            lines.append("        var found\(offset) = false")
            lines.append("        for element in databases {")
            lines.append("            guard \(needsVariable ? "var" : "let") database = element as? \(type) else {")
            lines.append("                continue")
            lines.append("            }")
            lines.append("            found\(offset) = true")
            for declaration in declarations {
                let call: String
                switch declaration.form {
                case .container:
                    call = "queries += database.declaredQueries"
                case .peer(let functionName, _):
                    call = "queries.append(database.\(functionName)DeclaredQuery())"
                }
                if let condition = declaration.condition {
                    lines.append("            #if \(condition)")
                    lines.append("            \(call)")
                    lines.append("            #endif")
                }
                else {
                    lines.append("            \(call)")
                }
            }
            lines.append("            break")
            lines.append("        }")
            lines.append("        if !found\(offset) {")
            lines.append("            throw XLDeclaredQueryError.missingDatabaseInstance(typeName: \"\(type)\")")
            lines.append("        }")
        }
        lines.append("        return queries")
        lines.append("    }")
        lines.append("}")
        return lines.joined(separator: "\n") + "\n"
    }
}
