//
//  DeclaredQueryRegistryRenderer.swift
//  SwiftQLDeclaredQueryDiscovery
//
//  Issue #659: renders the Swift source of a target's declared-query
//  registry from a scan of its declarations.
//

import Foundation


public enum DeclaredQueryRegistryRenderer {

    ///
    /// The registry's type name for a target: the target name as an upper
    /// camel case identifier, followed by `DeclaredQueries`.
    ///
    /// The target must not declare a type with this name itself.
    ///
    public static func typeName(forTarget target: String) -> String {
        var result = ""
        var capitalizesNext = true
        for character in target {
            guard character.isLetter || character.isNumber || character == "_" else {
                capitalizesNext = true
                continue
            }
            if capitalizesNext {
                result += String(character).uppercased()
            }
            else {
                result.append(character)
            }
            capitalizesNext = false
        }
        if result.isEmpty {
            result = "Target"
        }
        if let first = result.first, first.isNumber {
            result = "_" + result
        }
        return result + "DeclaredQueries"
    }

    ///
    /// The registry source for `targetName`.
    ///
    /// The registry is a public enum whose one method takes database
    /// instances as `Any`, so its public signature names no type the target
    /// might keep internal. For each database type that declares queries, it
    /// reads every declaration's generated member from the first matching
    /// instance, and throws when no instance of that type was passed.
    ///
    /// Everything that names a type or a declaration compiles under the same
    /// `#if` conditions the source does: an import under its own condition,
    /// a database type's whole block under the type's condition, and each
    /// call under the declaration's condition.
    ///
    public static func render(targetName: String, scan: DeclaredQueryScan) -> String {
        let registry = typeName(forTarget: targetName)
        var order: [String] = []
        var byType: [String: [DeclaredQueryDeclaration]] = [:]
        for declaration in scan.declarations {
            if byType[declaration.databaseType] == nil {
                order.append(declaration.databaseType)
            }
            byType[declaration.databaseType, default: []].append(declaration)
        }

        var lines: [String] = []
        lines.append("// Generated by SwiftQLDeclaredQueryRegistryPlugin from the @SQLQuery and")
        lines.append("// @SQLQueries declarations in target '\(targetName)'. Do not edit.")
        for skipped in scan.skipped {
            let fileName = URL(fileURLWithPath: skipped.file).lastPathComponent
            lines.append("//")
            lines.append("// Skipped \(fileName):\(skipped.line): \(skipped.reason)")
        }
        for excluded in scan.excluded {
            let fileName = URL(fileURLWithPath: excluded.file).lastPathComponent
            lines.append("//")
            lines.append("// Excluded \(fileName):\(excluded.line): \(excluded.reason)")
        }
        lines.append("")

        // One import per module and condition. Two spellings of one import
        // in a file (`import SwiftQL` and `internal import SwiftQL`) are an
        // "ambiguous implicit access level" error, so the first one found
        // wins, and SwiftQL is added only when no file imports it.
        var imports: [DeclaredQueryImport] = []
        for declaredImport in scan.imports where !imports.contains(where: {
            $0.module == declaredImport.module && $0.condition == declaredImport.condition
        }) {
            imports.append(declaredImport)
        }
        if !imports.contains(where: { $0.module == "SwiftQL" }) {
            imports.append(DeclaredQueryImport(declaration: "import SwiftQL", condition: nil, module: "SwiftQL"))
        }
        for declaredImport in imports where declaredImport.condition == nil {
            lines.append(declaredImport.declaration)
        }
        for declaredImport in imports {
            guard let condition = declaredImport.condition else {
                continue
            }
            lines.append("#if \(condition)")
            lines.append(declaredImport.declaration)
            lines.append("#endif")
        }
        lines.append("")

        lines.append("/// Every declared query in target '\(targetName)' that generated code can reach.")
        lines.append("public enum \(registry) {")
        lines.append("")
        lines.append("    /// The database types that declare queries, as the declarations spell them.")
        lines.append("    public static var databaseTypeNames: [String] {")
        lines.append("        var names: [String] = []")
        lines.append("        names.reserveCapacity(\(order.count))")
        for type in order {
            appendConditional(
                ["        names.append(\"\(type)\")"],
                condition: byType[type]?.first?.typeCondition,
                indent: "        ",
                to: &lines
            )
        }
        lines.append("        return names")
        lines.append("    }")
        lines.append("")
        lines.append("    /// The declared queries of the database instances in `databases`.")
        lines.append("    ///")
        lines.append("    /// - Throws: `XLDeclaredQueryError.missingDatabaseInstance` when")
        lines.append("    ///   `databases` holds no instance of a type that declares queries.")
        lines.append("    public static func queries(for databases: [Any]) throws -> [XLDeclaredQuery] {")
        lines.append("        var queries: [XLDeclaredQuery] = []")
        lines.append("        queries.reserveCapacity(databases.count)")
        for (offset, type) in order.enumerated() {
            let declarations = byType[type] ?? []
            let needsVariable = declarations.contains { declaration in
                if case .peer(_, true) = declaration.form {
                    return true
                }
                return false
            }
            var block: [String] = []
            block.append("        var found\(offset) = false")
            block.append("        for element in databases {")
            block.append("            guard \(needsVariable ? "var" : "let") database = element as? \(type) else {")
            block.append("                continue")
            block.append("            }")
            block.append("            found\(offset) = true")
            for declaration in declarations {
                let call: String
                switch declaration.form {
                case .container:
                    call = "            queries += database.declaredQueries"
                case .peer(let functionName, _):
                    call = "            queries.append(database.\(functionName)DeclaredQuery())"
                }
                appendConditional([call], condition: declaration.condition, indent: "            ", to: &block)
            }
            block.append("            break")
            block.append("        }")
            block.append("        if !found\(offset) {")
            block.append("            throw XLDeclaredQueryError.missingDatabaseInstance(typeName: \"\(type)\")")
            block.append("        }")
            lines.append("")
            appendConditional(block, condition: declarations.first?.typeCondition, indent: "        ", to: &lines)
        }
        lines.append("        return queries")
        lines.append("    }")
        lines.append("}")
        return lines.joined(separator: "\n") + "\n"
    }

    private static func appendConditional(
        _ block: [String],
        condition: String?,
        indent: String,
        to lines: inout [String]
    ) {
        guard let condition else {
            lines.append(contentsOf: block)
            return
        }
        lines.append("\(indent)#if \(condition)")
        lines.append(contentsOf: block)
        lines.append("\(indent)#endif")
    }
}
