import Foundation

import SwiftQL

/// Every query the demo's build-time validation checks.
///
/// `GRDBDatabase.declaredQueries` is generated by `@SQLQueries` from the
/// `Query` container in TodoReads.swift. A query added to that container is
/// listed here, and so in the next regenerated manifest, with no change to
/// this file or to the manifest generator.
///
/// The one addition is the list view's read, which is a statement rather than
/// a declaration (TodoFilteredRead.swift says why). It is described the way
/// the macro describes a declaration, so it lowers to a static descriptor
/// through the same runtime.
///
/// Public only so the manifest generator, a separate target, can read it.
public enum TodoDeclaredQueries {

    public static var all: [XLDeclaredQuery] {
        GRDBDatabase.declaredQueries + [filteredTodos]
    }

    static var filteredTodos: XLDeclaredQuery {
        XLDeclaredQuery(
            databaseType: GRDBDatabase.self,
            name: "filteredTodos",
            cardinality: .many,
            parameters: [
                XLDeclaredQueryParameter(name: "listID", valueType: TodoUUID.self),
                XLDeclaredQueryParameter(name: "includesCompleted", valueType: Bool.self),
                XLDeclaredQueryParameter(name: "includesActive", valueType: Bool.self),
                XLDeclaredQueryParameter(name: "overdueOnly", valueType: Bool.self),
                XLDeclaredQueryParameter(name: "referenceDate", valueType: TodoDate.self),
                XLDeclaredQueryParameter(name: "searchPattern", valueType: String.self),
                XLDeclaredQueryParameter(name: "sortOrder", valueType: Int.self),
            ],
            rowType: Todo.self,
            statement: { TodoFilteredRead.statement }
        )
    }
}
