import Foundation


/// Named, versioned SQLite codec presets for Foundation `UUID`.
///
/// SwiftQL does not retroactively conform `UUID` to any SwiftQL protocol, and
/// these presets do not require one: `XLValueCodecRegistry` looks codecs up by
/// the Swift value type's identity, not by a protocol witness, so a plain,
/// unmodified `UUID` participates in the contextual codec mechanism the same
/// way an application-owned domain type does. Register one of these presets
/// (or an application-owned codec with the same shape) as a database or query
/// default, or select it explicitly for one property, parameter, or result --
/// see <doc:CustomTypes>.
///
/// Both presets are named, versioned `XLValueCodec` values, not database
/// defaults. Registering a preset never changes existing storage by itself.
/// Adding a preset's `identity.key` to `defaultCodecKeys`, or switching an
/// existing default between ``text`` and ``blob``, is a data migration: rows
/// already written keep their prior representation until they are rewritten
/// with an explicit `UPDATE`. The two representations are not bytewise
/// interchangeable and do not sort the same way; see each preset's discussion
/// below.
///
/// PostgreSQL and other dialects with a native `UUID` column type are
/// expected to define their own dialect-specific codec (targeting that
/// dialect's `XLValueCodingDialect` conformance) rather than reuse either
/// preset here. Nothing about this Swift-side `UUID` domain type changes when
/// a different dialect supplies a different mapping.
public enum XLUUIDValueCodec {

    /// Canonical lowercase, hyphenated text, e.g.
    /// `"e02f7c60-8c7f-4c68-8b62-6f0f1a2b3c4d"` (36 UTF-8 bytes), matching
    /// `UUID.uuidString.lowercased()`.
    ///
    /// - Storage class: SQLite `TEXT`.
    /// - Case and canonicalization: always encoded lowercase. Decoding
    ///   accepts any case `Foundation.UUID(uuidString:)` accepts (that
    ///   initializer is case-insensitive), but rejects surrounding
    ///   whitespace, missing hyphens, or a `urn:uuid:` prefix.
    /// - Equality: byte-for-byte string equality after lowercasing. Two
    ///   `UUID` values that are Swift-equal always encode to the same text
    ///   and are therefore also SQL `=`-equal.
    /// - Ordering: SQLite's default `BINARY` collation over the hyphenated
    ///   lowercase string, i.e. lexicographic UTF-8 byte order. This is
    ///   **not** the same ordering as ``blob``'s raw 16-byte order, and
    ///   generally does not match creation order unless the `UUID` values
    ///   themselves were generated by a time-ordered scheme whose text
    ///   representation happens to sort lexicographically.
    /// - Indexing: an index entry is 36 bytes per row -- larger than
    ///   ``blob``'s 16 bytes -- but human-readable in ad hoc queries,
    ///   `sqlite3` shell output, and exported data.
    /// - Migration: switching a column between ``text`` and ``blob`` changes
    ///   its on-disk representation. Existing rows must be rewritten
    ///   explicitly (for example `UPDATE t SET id = ...`); SwiftQL never
    ///   detects or converts a stored representation automatically.
    public static let text: XLValueCodec<UUID, XLSQLiteDialect> = XLValueCodec(
        key: XLValueCodecKey(id: "swiftql.uuid.text", version: 1),
        valueTypeIdentifier: _xlUUIDValueTypeIdentifier,
        dialectIdentifier: XLSQLiteDialect.identity,
        storageIdentifier: XLValueStorageIdentifier(
            rawValue: XLSQLiteStorageClass.text.rawValue
        ),
        encode: { value, _, _ in
            .text(value.uuidString.lowercased())
        },
        decode: { value, _, context in
            guard case .text(let text) = value else {
                throw XLUUIDValueCodecError.unexpectedDialectValue(
                    describing: value,
                    context: context
                )
            }
            guard let uuid = UUID(uuidString: text) else {
                throw XLUUIDValueCodecError.invalidText(text, context: context)
            }
            return uuid
        }
    )

    /// The canonical 16-byte binary layout Foundation exposes as `UUID.uuid`:
    /// the big-endian `time_low` / `time_mid` / `time_hi_and_version` /
    /// `clock_seq_hi_and_reserved` / `clock_seq_low` / `node` field order
    /// defined by RFC 4122, with no additional byte swapping or reordering.
    /// This is the same wire format produced by `uuid_generate_v4()`,
    /// PostgreSQL's `gen_random_uuid()`, and most other UUID libraries; it is
    /// **not** rearranged into any database- or platform-specific "sortable"
    /// or "sequential" layout.
    ///
    /// - Storage class: SQLite `BLOB`, exactly 16 bytes.
    /// - Case/canonicalization: not applicable; a `BLOB` has no case.
    /// - Equality: byte-for-byte `Data` equality, identical to
    ///   `Foundation.UUID` equality -- the same logical UUID always encodes
    ///   to the same 16 bytes.
    /// - Ordering: SQLite's default `BINARY` collation over the 16 raw
    ///   bytes in RFC 4122 field order. This is **not** the same ordering as
    ///   ``text``'s hyphenated lowercase string order. The two presets always
    ///   agree on equality but not on ordering, so do not mix them within a
    ///   single `ORDER BY`, range predicate, or index-supported comparison.
    /// - Indexing: a 16-byte fixed-width index entry, roughly 44% of
    ///   ``text``'s 36-byte entry -- usually the more compact and
    ///   cache-friendlier choice for a primary key or a frequently indexed
    ///   column.
    /// - Migration: see ``text``.
    public static let blob: XLValueCodec<UUID, XLSQLiteDialect> = XLValueCodec(
        key: XLValueCodecKey(id: "swiftql.uuid.blob", version: 1),
        valueTypeIdentifier: _xlUUIDValueTypeIdentifier,
        dialectIdentifier: XLSQLiteDialect.identity,
        storageIdentifier: XLValueStorageIdentifier(
            rawValue: XLSQLiteStorageClass.blob.rawValue
        ),
        encode: { value, _, _ in
            var raw = value.uuid
            let data = withUnsafeBytes(of: &raw) { Data($0) }
            return .blob(data)
        },
        decode: { value, _, context in
            guard case .blob(let data) = value else {
                throw XLUUIDValueCodecError.unexpectedDialectValue(
                    describing: value,
                    context: context
                )
            }
            guard data.count == 16 else {
                throw XLUUIDValueCodecError.invalidBlobLength(
                    data.count,
                    context: context
                )
            }
            // `Data` gives no alignment guarantee for its backing storage,
            // so an aligned `load(as: uuid_t.self)` can trap depending on
            // platform and optimization level. `copyBytes` performs an
            // unaligned byte-wise copy instead.
            var raw: uuid_t = (0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
            withUnsafeMutableBytes(of: &raw) { destination in
                _ = data.copyBytes(to: destination)
            }
            return UUID(uuid: raw)
        }
    )
}


/// The stable Swift-value identity shared by both ``XLUUIDValueCodec``
/// presets. Both presets persist the same logical `UUID` value; only their
/// SQLite storage representation differs, which is what `storageIdentifier`
/// (not `valueTypeIdentifier`) distinguishes.
private let _xlUUIDValueTypeIdentifier = XLValueTypeIdentifier(
    rawValue: "foundation.UUID"
)


/// Structured decoding failures specific to the built-in UUID presets.
///
/// `XLValueCodec` wraps whatever a decode closure throws into
/// ``XLValueCodecError/decodingFailed(codec:context:message:)`` using
/// `String(describing:)`, not `localizedDescription`, and already carries the
/// failing codec's key and coding context. This type supplies the
/// UUID-specific detail -- the invalid text, or the wrong byte count -- that
/// becomes that wrapped error's message; `CustomStringConvertible` forwards
/// to `errorDescription` so `String(describing:)` renders that same
/// human-readable text instead of the synthesized case dump.
public enum XLUUIDValueCodecError:
    Error,
    Equatable,
    Sendable,
    LocalizedError,
    CustomStringConvertible
{

    /// The stored text is not a UUID `Foundation.UUID(uuidString:)` accepts.
    case invalidText(String, context: XLValueCodingContext)

    /// The stored `BLOB` is not exactly 16 bytes.
    case invalidBlobLength(Int, context: XLValueCodingContext)

    /// Defensive only: `XLValueCodec` already rejects a storage-class
    /// mismatch (via `XLValueCodecError.storageMismatch`) before invoking
    /// either preset's decode closure, so this case is unreachable through
    /// the public codec API. It remains to keep both decode closures total.
    case unexpectedDialectValue(
        describing: XLSQLiteValue,
        context: XLValueCodingContext
    )

    public var errorDescription: String? {
        switch self {
        case .invalidText(let text, let context):
            return "\"\(text)\" is not a valid UUID at \(context)."
        case .invalidBlobLength(let length, let context):
            return "A UUID BLOB must be exactly 16 bytes, received \(length) at \(context)."
        case .unexpectedDialectValue(let value, let context):
            return "Expected a UUID-compatible SQLite storage class, received \(value) at \(context)."
        }
    }

    public var description: String {
        // `errorDescription`'s switch is exhaustive and every case returns a
        // concrete string, so this is never the fallback in practice; it
        // exists only to keep `description` total without recursing back
        // into `String(describing:)`, which would call this property again.
        errorDescription ?? "XLUUIDValueCodecError"
    }
}
