import Foundation
import SwiftQLSQLiteBuildValidationValidator


/// Renders verified index recommendations as a generated, checked-in SQL
/// artifact.
///
/// ## Why SQL and not a rewritten declaration
///
/// This milestone has no typed index-declaration surface to rewrite. Typed
/// DDL is v2 work (#139), and until a declaration site exists there is
/// nothing for SwiftSyntax to edit — inventing one here would be inventing
/// API. So the tool generates a standalone artifact and says so, in the
/// artifact itself. When the typed surface lands, the rewrite replaces this
/// renderer; the command's contract does not change.
///
/// ## Why the bytes are a pure function of the recommendations
///
/// Apply mode must be idempotent: running it twice on unchanged advice has to
/// be a proven no-op, not a file with a new timestamp in it. So this renderer
/// takes no clock, no host, and no path, and orders everything it emits.
public enum SQLiteIndexAdvisorArtifact {

    public static let generatedHeaderMarker = "Generated by swiftql-index-advisor."

    /// Renders `recommendations` as SQL.
    ///
    /// `sourceDescription` names where the advice came from — a path, or any
    /// stable label. It is written into the header, so a caller that wants
    /// byte-stable output across machines must pass a stable value.
    public static func sql(
        for recommendations: SQLiteBuildValidationIndexRecommendationSet,
        sourceDescription: String
    ) -> String {
        var lines = [
            "-- \(generatedHeaderMarker) Do not edit by hand.",
            "--",
            "-- Source: \(sourceDescription)",
            "-- Improvement rule: \(recommendations.improvementRuleVersion)",
            "--",
            "-- Every statement below was verified by creating the index on a",
            "-- disposable copy of the pinned snapshot and re-planning the",
            "-- statement that motivated it. The before and after plans are",
            "-- recorded beside each one.",
        ]
        if recommendations.recommendations.isEmpty {
            lines.append("--")
            lines.append("-- No verified recommendations.")
            return lines.joined(separator: "\n") + "\n"
        }

        for recommendation in recommendations.recommendations {
            let candidate = recommendation.candidate
            lines.append("")
            lines.append("-- \(candidate.table) (\(candidate.columns.map(\.name).joined(separator: ", ")))")
            lines.append("-- Motivated by: \(candidate.sourceQueryIDs.joined(separator: ", "))")
            lines.append("-- Before: \(planSummary(recommendation.beforePlan))")
            lines.append("-- After:  \(planSummary(recommendation.afterPlan))")
            lines.append("-- Why:    \(recommendation.improvementReason)")
            lines.append("-- Cost:   \(recommendation.writeCostNote)")
            // `IF NOT EXISTS`, because this artifact is meant to be executed
            // against a real database on every launch or migration, and the
            // second execution must be a no-op rather than an error.
            lines.append(candidate.ddl(ifNotExists: true) + ";")
        }
        return lines.joined(separator: "\n") + "\n"
    }

    /// A one-line rendering of a plan, used in the artifact's comments.
    static func planSummary(_ roots: [SQLiteBuildValidationPlanNode]) -> String {
        guard !roots.isEmpty else {
            return "(no plan nodes)"
        }
        return roots.map(\.detail).joined(separator: " | ")
    }
}


extension SQLiteBuildValidationIndexCandidate {
    /// The candidate's DDL, optionally as `CREATE INDEX IF NOT EXISTS`.
    ///
    /// Verification deliberately uses the plain form: creating an index that
    /// already exists there would mean the scratch copy was not clean, and
    /// that must fail rather than pass quietly. A checked-in artifact is the
    /// opposite case — it runs against a real database repeatedly, and the
    /// second run must do nothing.
    public func ddl(ifNotExists: Bool) -> String {
        guard ifNotExists else {
            return ddl
        }
        return ddl.replacingOccurrences(
            of: "CREATE INDEX ",
            with: "CREATE INDEX IF NOT EXISTS ",
            options: [.anchored]
        )
    }
}
