-- Golden PostgreSQL rendering for the v2 dialect seam (#675).
--
-- Generated by PostgreSQLGoldenRenderingTests. Do not edit by hand:
-- run the suite with SWIFTQL_UPDATE_POSTGRESQL_GOLDEN=1 instead.
--
-- A rendering proof only. SwiftQL has no PostgreSQL driver and claims
-- no PostgreSQL support. Known gaps are recorded in
-- Documentation/Architecture/PostgreSQLRenderingGaps.md.

-- select-all
SELECT "t0"."name" AS "name" FROM "Person" AS "t0"

-- equality-on-non-optional
SELECT "t0"."name" AS "name" FROM "Person" AS "t0" WHERE ("t0"."age" = 42)

-- null-safe-equality-on-optional
SELECT "t0"."name" AS "name" FROM "Person" AS "t0" WHERE ("t0"."nickname" IS NOT DISTINCT FROM "t0"."name")

-- null-test
SELECT "t0"."name" AS "name" FROM "Person" AS "t0" WHERE ("t0"."nickname" IS NULL)

-- regex-match
SELECT "t0"."name" AS "name" FROM "Person" AS "t0" WHERE ("t0"."name" ~ '^A.*n$')

-- collate-binary
SELECT "t0"."name" AS "name" FROM "Person" AS "t0" WHERE (("t0"."name" COLLATE "C") = "t0"."name")

-- insert-with-values
INSERT INTO "Person" AS "t0" ("id","name","nickname","age","avatar") VALUES ('a','Ada',NULL,36,'\x01')

-- insert-or-ignore
-- !! GAP G4: the OR IGNORE conflict algorithm is dropped. This statement raises on conflict instead of skipping the row. A driver must refuse it, not run it.
INSERT INTO "Person" AS "t0" ("id","name","nickname","age","avatar") VALUES ('a','Ada',NULL,36,'\x01')

-- blob-literal
'\xdeadbeef'

-- text-literal-with-quote
'O''Hara'

-- conditional
CASE WHEN 1 THEN 2 ELSE 3 END

-- named-parameter-twice
$1 $1

-- mixed-parameters
$1 $2 $3

