name: Deploy DocC

on:
  push:
    branches: ["main"]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy DocC
        id: deployment
        uses: swiftlang/swift-docc-plugin@v1.4.5
        with:
          target: SwiftQL
          hosting-base-path: /swiftql
          output-path: "docs"
          transform-for-static-hosting: "true"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
